namespace Creuser.Web.Branding;

/// <summary>
/// Brand palette overrides — keys map 1:1 to Quasar's <c>setBrand()</c>
/// arguments and the <c>--q-*</c> CSS variables. Hex strings (e.g. <c>#3b82f6</c>),
/// any value <c>null</c> means "fall through to the baked-in default".
/// </summary>
public sealed record BrandPalette(
    string? Primary = null,
    string? Secondary = null,
    string? Accent = null,
    string? Positive = null,
    string? Negative = null,
    string? Info = null,
    string? Warning = null,
    string? Dark = null,
    string? DarkPage = null
);

/// <summary>
/// Creuser-specific chrome tokens — header bg, sidebar bg, surface, borders,
/// foreground colors. These map to <c>--cr-*</c> CSS variables. Any value
/// <c>null</c> falls through to the baked-in theme defaults in
/// <c>theme.scss</c>.
/// </summary>
public sealed record ChromeTokens(
    string? BgPage = null,
    string? BgSurface = null,
    string? BgHeader = null,
    string? BgSidebar = null,
    string? BgElevated = null,
    string? FgPrimary = null,
    string? FgSecondary = null,
    string? FgTertiary = null,
    string? BorderSubtle = null,
    string? BorderDefault = null,
    string? BorderStrong = null
);

/// <summary>
/// Singleton branding configuration. Stored as a row in <c>cr.app_settings</c>
/// under key <c>branding</c>. Read on every page load (the <c>/api/branding</c>
/// endpoint is anonymous so the login screen can theme itself); written by
/// admins from the Branding settings page.
///
/// <para>
/// Chrome tokens are stored per-mode: <c>Chrome</c> applies in dark mode,
/// <c>ChromeLight</c> in light mode. The Branding UI shows a single column
/// of pickers that targets whichever mode is currently active so admins
/// don't have to manage two parallel grids.
/// </para>
///
/// <para>
/// <c>CustomCss</c> is the universal escape hatch — admin-authored CSS
/// injected after the structured overrides, so it wins over them. Use
/// <c>body.body--light selector { ... }</c> or <c>body.body--dark selector { ... }</c>
/// for mode-specific rules.
/// </para>
/// </summary>
public sealed record BrandingConfig(
    string ProductName,
    string? LogoUrl,
    string? FaviconUrl,
    string? LoginBackgroundUrl,
    string? LoginTagline, // small subhead under the product name on the login page
    string Mode, // "dark" or "light" — admin's default for users on `auto`
    BrandPalette Palette,
    ChromeTokens Chrome, // applied in dark mode
    ChromeTokens ChromeLight, // applied in light mode
    string? FontFamily, // CSS font-family list, e.g. `"Inter", system-ui, sans-serif`
    string? FontFamilyMono, // CSS font-family list for monospace surfaces (script editor, code, etc.)
    string? CustomCss, // appended to the injected style tag last; wins over the structured overrides
    string? FooterText,
    string? SupportEmail
)
{
    public static BrandingConfig Default { get; } =
        new(
            ProductName: "Creuser",
            // The SPA bundles `public/logo.svg` and `public/favicon.ico`
            // (regenerated by icongenie from the same SVG). Default to those
            // so a fresh deployment's sidebar, login page, and browser tab
            // all show the Creuser brand without any admin upload step.
            // An admin upload replaces LogoUrl with `/api/branding/assets/...`.
            LogoUrl: "/logo.svg",
            FaviconUrl: "/favicon.ico",
            LoginBackgroundUrl: null,
            LoginTagline: "Workflow & agent orchestration",
            Mode: "dark",
            Palette: new BrandPalette(),
            Chrome: new ChromeTokens(),
            ChromeLight: new ChromeTokens(),
            FontFamily: null,
            FontFamilyMono: null,
            CustomCss: null,
            FooterText: null,
            SupportEmail: null
        );
}
