namespace Creuser.Web.Branding;

/// <summary>
/// Brand palette overrides — keys map 1:1 to Quasar's <c>setBrand()</c>
/// arguments and the <c>--q-*</c> CSS variables. Hex strings (e.g. <c>#3b82f6</c>),
/// any value <c>null</c> means "fall through to the baked-in default".
/// </summary>
public sealed record BrandPalette(
    string? Primary = null,
    string? Secondary = null,
    string? Accent = null,
    string? Positive = null,
    string? Negative = null,
    string? Info = null,
    string? Warning = null,
    string? Dark = null,
    string? DarkPage = null
);

/// <summary>
/// Creuser-specific chrome tokens — header bg, sidebar bg, surface, borders,
/// foreground colors. These map to <c>--cr-*</c> CSS variables. Any value
/// <c>null</c> falls through to the baked-in theme defaults in
/// <c>theme.scss</c>.
/// </summary>
public sealed record ChromeTokens(
    string? BgPage = null,
    string? BgSurface = null,
    string? BgHeader = null,
    string? BgSidebar = null,
    string? BgElevated = null,
    string? FgPrimary = null,
    string? FgSecondary = null,
    string? FgTertiary = null,
    string? BorderSubtle = null,
    string? BorderDefault = null,
    string? BorderStrong = null
);

/// <summary>
/// Singleton branding configuration. Stored as a row in <c>cr.app_settings</c>
/// under key <c>branding</c>. Read on every page load (the <c>/api/branding</c>
/// endpoint is anonymous so the login screen can theme itself); written by
/// admins from the Branding settings page.
///
/// <para>
/// Palette, chrome, and logo are stored per-mode: <c>Palette</c> /
/// <c>Chrome</c> / <c>LogoUrl</c> apply in dark mode, <c>PaletteLight</c> /
/// <c>ChromeLight</c> / <c>LogoUrlLight</c> in light mode. The Branding UI
/// exposes both slots side-by-side so an admin can pick (e.g.) a Dracula
/// dark base and a Solarized Light light base and edit each mode
/// independently. The user's header theme toggle drives which slot the
/// browser renders at any moment.
/// </para>
///
/// <para>
/// <c>CustomCss</c> is the universal escape hatch — admin-authored CSS
/// injected after the structured overrides, so it wins over them. Use
/// <c>body.body--light selector { ... }</c> or <c>body.body--dark selector { ... }</c>
/// for mode-specific rules.
/// </para>
/// </summary>
public sealed record BrandingConfig(
    string ProductName,
    string? LogoUrl, // applied in dark mode
    string? LogoUrlLight, // applied in light mode; falls through to LogoUrl when unset
    string? FaviconUrl,
    string? LoginBackgroundUrl,
    string? LoginTagline, // small subhead under the product name on the login page
    string Mode, // "dark" or "light" — admin's default for users on `auto`
    BrandPalette Palette, // applied in dark mode
    BrandPalette PaletteLight, // applied in light mode
    ChromeTokens Chrome, // applied in dark mode
    ChromeTokens ChromeLight, // applied in light mode
    string? FontFamily, // CSS font-family list, e.g. `"Inter", system-ui, sans-serif`
    string? FontFamilyMono, // CSS font-family list for monospace surfaces (script editor, code, etc.)
    string? CustomCss, // appended to the injected style tag last; wins over the structured overrides
    string? FooterText,
    string? SupportEmail
)
{
    public static BrandingConfig Default { get; } =
        new(
            ProductName: "Creuser",
            // The SPA bundles three Creuser logo assets in `public/`:
            //   - `logo-dark.svg`  — tuned for dark surfaces (sidebar, dark login)
            //   - `logo-light.svg` — tuned for light surfaces
            //   - `logo.svg`       — generic standalone copy (kept as a stable URL
            //                        for any external reference / docs / OG image)
            // Plus `favicon.ico` (regenerated by icongenie). Default to the
            // per-mode pair so a fresh deployment's sidebar / login / browser
            // tab pick the right glyph for whichever theme the user is in,
            // without any admin upload step. An admin upload replaces
            // LogoUrl / LogoUrlLight with `/api/branding/assets/...` URLs.
            LogoUrl: "/logo-dark.svg",
            LogoUrlLight: "/logo-light.svg",
            FaviconUrl: "/favicon.ico",
            LoginBackgroundUrl: null,
            LoginTagline: "Workflow & agent orchestration",
            Mode: "dark",
            // Palette + chrome values mirror the bundled SCSS defaults
            // (`src/css/quasar.variables.scss` for the brand palette,
            // `src/css/theme.scss` for chrome tokens). Carried explicitly so
            // a fresh deployment's saved BrandingConfig matches the Creuser
            // Dark + Creuser Light presets exactly — the SPA's
            // detectActivePreset uses strict canonical equality, so empty
            // records here would render as "Custom" in the picker.
            //
            // If any of the SCSS values change, update both that file *and*
            // the matching constants in
            // `src/Creuser.Web.Spa/src/css/palettes/registry.ts`
            // (CREUSER_PALETTE / CREUSER_DARK_CHROME / CREUSER_LIGHT_CHROME)
            // *and* this record. The two SCSS files carry header comments
            // pointing at registry.ts as a sync reminder.
            Palette: new BrandPalette(
                Primary: "#5c7e62",
                Secondary: "#7c9a82",
                Accent: "#d7a06b",
                Positive: "#22c55e",
                Negative: "#ef4444",
                Info: "#0ea5e9",
                Warning: "#f59e0b"
            ),
            PaletteLight: new BrandPalette(
                Primary: "#5c7e62",
                Secondary: "#7c9a82",
                Accent: "#d7a06b",
                Positive: "#22c55e",
                Negative: "#ef4444",
                Info: "#0ea5e9",
                Warning: "#f59e0b"
            ),
            Chrome: new ChromeTokens(
                BgPage: "#0c2422",
                BgSurface: "#143734",
                BgHeader: "#1a4441",
                BgSidebar: "#1a4441",
                BgElevated: "#225855",
                FgPrimary: "rgba(255, 255, 255, 0.95)",
                FgSecondary: "rgba(255, 255, 255, 0.72)",
                FgTertiary: "rgba(255, 255, 255, 0.5)",
                BorderSubtle: "rgba(255, 255, 255, 0.08)",
                BorderDefault: "rgba(255, 255, 255, 0.14)",
                BorderStrong: "rgba(255, 255, 255, 0.28)"
            ),
            ChromeLight: new ChromeTokens(
                BgPage: "#fafafa",
                BgSurface: "#ffffff",
                BgHeader: "#ffffff",
                BgSidebar: "#f6f6f7",
                BgElevated: "#ececee",
                FgPrimary: "rgba(0, 0, 0, 0.88)",
                FgSecondary: "rgba(0, 0, 0, 0.55)",
                FgTertiary: "rgba(0, 0, 0, 0.3)",
                BorderSubtle: "rgba(0, 0, 0, 0.06)",
                BorderDefault: "rgba(0, 0, 0, 0.12)",
                BorderStrong: "rgba(0, 0, 0, 0.24)"
            ),
            FontFamily: null,
            FontFamilyMono: null,
            CustomCss: null,
            FooterText: null,
            SupportEmail: null
        );
}
