using System.Text.Json;
using Creuser.Core.Repositories;

namespace Creuser.Web.Workspaces;

/// <summary>
/// Seeds the platform-shipped Home dashboard + Operations group on workspace
/// creation. Idempotent — re-running only inserts rows that don't already
/// exist (matched by <c>(workspace_id, slug)</c>) so a re-seed after a
/// botched deploy can't clobber user-edited Home dashboards.
///
/// <para>
/// The seed runs as a fire-and-forget continuation of
/// <see cref="Creuser.Web.Endpoints.WorkspacesEndpoints.Create"/> — failures
/// log + don't fail the create. A workspace without seeded dashboards still
/// renders cleanly in the SPA (empty icon bar, manual "Create dashboard"
/// flow); the seed is convenience, not a hard requirement.
/// </para>
/// </summary>
public sealed class DashboardSeeder : IDashboardSeeder
{
    private readonly IDashboardStore _store;

    public DashboardSeeder(IDashboardStore store)
    {
        _store = store;
    }

    public async Task SeedDefaultsAsync(
        Guid workspaceId,
        Guid? createdBy = null,
        CancellationToken ct = default
    )
    {
        var now = DateTime.UtcNow;

        // 1. Home — standalone, two-column placeholder layout. Layout JSON
        // is the SPA's responsibility on first edit; we ship a minimal
        // dockview state that places three widgets in a sensible default.
        var home = await _store.FindBySlugAsync(workspaceId, "home", ct);
        if (home is null)
        {
            await _store.CreateAsync(
                new Dashboard(
                    Id: Guid.Empty, // generated by DB default
                    WorkspaceId: workspaceId,
                    GroupId: null,
                    Slug: "home",
                    Name: "Home",
                    Icon: "home",
                    LayoutJson: SerializeLayout(HomeLayout()),
                    WidgetsJson: SerializeWidgets(HomeWidgets()),
                    Position: 0,
                    IsDefault: true,
                    CreatedAt: now,
                    UpdatedAt: now,
                    CreatedBy: createdBy
                ),
                ct
            );
        }

        // 2. Operations group + three dashboards.
        var ops = await _store.FindGroupBySlugAsync(workspaceId, "operations", ct);
        if (ops is null)
        {
            ops = await _store.CreateGroupAsync(
                new DashboardGroup(
                    Id: Guid.Empty,
                    WorkspaceId: workspaceId,
                    Slug: "operations",
                    Name: "Operations",
                    Icon: "bolt",
                    Position: 10,
                    IsDefault: true,
                    CreatedAt: now,
                    UpdatedAt: now,
                    CreatedBy: createdBy
                ),
                ct
            );
        }

        await EnsureGroupedDashboardAsync(
            workspaceId,
            ops.Id,
            slug: "runs",
            name: "Runs",
            icon: "play_circle",
            position: 0,
            widgets: new[] { Widget("RunsList", new { limit = 50 }) },
            createdBy: createdBy,
            now: now,
            ct: ct
        );
        await EnsureGroupedDashboardAsync(
            workspaceId,
            ops.Id,
            slug: "scripts",
            name: "Scripts",
            icon: "description",
            position: 10,
            widgets: new[] { Widget("JobScriptList", new { limit = 100 }) },
            createdBy: createdBy,
            now: now,
            ct: ct
        );
        await EnsureGroupedDashboardAsync(
            workspaceId,
            ops.Id,
            slug: "schedules",
            name: "Schedules",
            icon: "schedule",
            position: 20,
            widgets: new[] { Widget("ScheduleList", new { limit = 100 }) },
            createdBy: createdBy,
            now: now,
            ct: ct
        );
    }

    private async Task EnsureGroupedDashboardAsync(
        Guid workspaceId,
        Guid groupId,
        string slug,
        string name,
        string icon,
        int position,
        IReadOnlyList<object> widgets,
        Guid? createdBy,
        DateTime now,
        CancellationToken ct
    )
    {
        var existing = await _store.FindBySlugAsync(workspaceId, slug, ct);
        if (existing is not null)
            return;

        await _store.CreateAsync(
            new Dashboard(
                Id: Guid.Empty,
                WorkspaceId: workspaceId,
                GroupId: groupId,
                Slug: slug,
                Name: name,
                Icon: icon,
                LayoutJson: SerializeLayout(SinglePaneLayout(widgets)),
                WidgetsJson: SerializeWidgets(widgets),
                Position: position,
                IsDefault: true,
                CreatedAt: now,
                UpdatedAt: now,
                CreatedBy: createdBy
            ),
            ct
        );
    }

    // ============================================================
    // Default layout shapes
    //
    // These are loose `object` literals serialized to JSON so the SPA's
    // dockview-vue picks them up as a SerializedDockview. The shapes are
    // intentionally minimal — dockview will normalize them on first
    // render and the user's first save persists the canonical form.
    // ============================================================

    private static IReadOnlyList<object> HomeWidgets() =>
        new[]
        {
            Widget("RunsList", new { limit = 10 }),
            Widget("JobScriptList", new { limit = 10 }),
            Widget("ScheduleList", new { limit = 10 }),
        };

    private static object Widget(string widgetType, object props) =>
        new
        {
            id = "w-" + Guid.NewGuid().ToString("N")[..8],
            widgetType,
            props,
        };

    /// <summary>
    /// Three-pane layout — runs on the left, scripts top-right, schedules
    /// bottom-right. A reasonable default for a fresh workspace.
    /// </summary>
    private static object HomeLayout()
    {
        // Mixed leaf+branch nodes share a tagged shape with a string `type`,
        // so the array holds them as `object` to keep C# happy with anonymous
        // type inference. dockview ignores the .NET-side typing on the wire.
        var leafRuns = (object)
            new
            {
                type = "leaf",
                data = new
                {
                    views = new[] { "p-runs" },
                    activeView = "p-runs",
                    id = "g-1",
                },
                size = 600,
            };
        var leafScripts = (object)
            new
            {
                type = "leaf",
                data = new
                {
                    views = new[] { "p-scripts" },
                    activeView = "p-scripts",
                    id = "g-2",
                },
                size = 350,
            };
        var leafSchedules = (object)
            new
            {
                type = "leaf",
                data = new
                {
                    views = new[] { "p-schedules" },
                    activeView = "p-schedules",
                    id = "g-3",
                },
                size = 350,
            };
        var rightBranch = (object)
            new
            {
                type = "branch",
                data = new[] { leafScripts, leafSchedules },
                size = 600,
            };
        return new
        {
            grid = new
            {
                root = new
                {
                    type = "branch",
                    data = new[] { leafRuns, rightBranch },
                    size = 700,
                },
                width = 1200,
                height = 700,
                orientation = "HORIZONTAL",
            },
            panels = new
            {
                pRuns = new { id = "p-runs", title = "Runs" },
                pScripts = new { id = "p-scripts", title = "Scripts" },
                pSchedules = new { id = "p-schedules", title = "Schedules" },
            },
        };
    }

    private static object SinglePaneLayout(IReadOnlyList<object> widgets)
    {
        var panelId = "p-only";
        return new
        {
            grid = new
            {
                root = new
                {
                    type = "leaf",
                    data = new
                    {
                        views = new[] { panelId },
                        activeView = panelId,
                        id = "g-1",
                    },
                    size = 1200,
                },
                width = 1200,
                height = 700,
                orientation = "HORIZONTAL",
            },
            panels = new Dictionary<string, object>
            {
                [panelId] = new { id = panelId, title = "" },
            },
        };
    }

    private static string SerializeLayout(object layout) => JsonSerializer.Serialize(layout);

    private static string SerializeWidgets(IReadOnlyList<object> widgets) =>
        JsonSerializer.Serialize(widgets);
}

public interface IDashboardSeeder
{
    /// <summary>
    /// Idempotently insert the default Home dashboard + Operations group +
    /// its child dashboards for a workspace. Existing rows are left
    /// untouched — admins who delete a default dashboard don't get it
    /// back on next seed.
    /// </summary>
    Task SeedDefaultsAsync(
        Guid workspaceId,
        Guid? createdBy = null,
        CancellationToken ct = default
    );
}
