using System.Text.Json.Nodes;
using Creuser.Core.Projections;
using Creuser.Projections.Accessors;

namespace Creuser.Projections.Schema;

/// <summary>
/// Generates a JSON Schema for the convention YAML grammar, populated with the
/// live computed-accessor registry's namespaces. Authors reference the schema
/// via a <c># yaml-language-server: $schema=…</c> line at the top of their
/// convention files; IDEs (VS Code, Cursor, JetBrains) then provide
/// autocomplete and validation with no plugin work.
///
/// <para>
/// The schema is generated by hand (no <c>JsonSchema.Net.Generation</c>
/// dependency) because the surface area is small and we want full control
/// over the descriptions, defaults, and accessor enum.
/// </para>
/// </summary>
public static class ConventionSchemaGenerator
{
    public const string SchemaVersion = "v1";

    public static JsonObject Generate(
        ComputedAccessorRegistry? registry = null,
        IReadOnlyCollection<string>? workspaceKinds = null
    )
    {
        registry ??= ComputedAccessorRegistry.Default;

        var accessorEnum = new JsonArray();
        foreach (var (key, _) in registry.AllFields.OrderBy(kv => kv.Key, StringComparer.Ordinal))
            accessorEnum.Add(JsonValue.Create(key));

        var targetKindEnum = new JsonArray { "any" };
        if (workspaceKinds is not null)
        {
            foreach (var k in workspaceKinds.OrderBy(s => s, StringComparer.Ordinal))
                targetKindEnum.Add(JsonValue.Create(k));
        }

        var schema = new JsonObject
        {
            ["$schema"] = "https://json-schema.org/draft/2020-12/schema",
            ["$id"] = $"https://creuser.local/api/conventions/schema/{SchemaVersion}.json",
            ["title"] = "Creuser convention",
            ["description"] = "Schema for `.creuser/conventions/*.yaml` documents.",
            ["type"] = "object",
            ["required"] = new JsonArray { "id", "match" },
            ["additionalProperties"] = false,
            ["properties"] = new JsonObject
            {
                ["id"] = new JsonObject
                {
                    ["type"] = "string",
                    ["description"] = "Unique kind id within the workspace.",
                    ["pattern"] = "^[a-z][a-z0-9_]*$",
                },
                ["description"] = StringField("Free-text description of the convention."),
                ["extends"] = new JsonObject
                {
                    ["type"] = "string",
                    ["description"] =
                        "Reference to a bundled standard (e.g. `creuser:standard/adr`) to merge in.",
                    ["pattern"] = "^creuser:standard/[a-z0-9-]+$",
                },
                ["priority"] = new JsonObject
                {
                    ["type"] = "integer",
                    ["default"] = 0,
                    ["description"] = "Higher wins on glob conflict.",
                },
                ["match"] = MatchSchema(),
                ["slug"] = SlugSchema(),
                ["metadata"] = MetadataSchema(accessorEnum),
                ["relationships"] = new JsonObject
                {
                    ["type"] = "array",
                    ["description"] =
                        "One typed edge per rule. Each rule renders as a navigable folder under matching entities in the CDFS.",
                    ["items"] = RelationshipSchema(targetKindEnum),
                },
                ["validation"] = new JsonObject
                {
                    ["type"] = "array",
                    ["items"] = new JsonObject
                    {
                        ["type"] = "object",
                        ["required"] = new JsonArray { "rule", "expr" },
                        ["additionalProperties"] = false,
                        ["properties"] = new JsonObject
                        {
                            ["rule"] = StringField("Rule label surfaced in find_invalid output."),
                            ["expr"] = StringField("Expression evaluated against the entity."),
                        },
                    },
                },
                ["actions"] = new JsonObject
                {
                    ["type"] = "array",
                    ["description"] = "Right-click actions surfaced in the CDFS per-row menu.",
                    ["items"] = ActionSchema(),
                },
            },
        };
        return schema;
    }

    private static JsonObject MatchSchema() =>
        new()
        {
            ["type"] = "object",
            ["required"] = new JsonArray { "glob" },
            ["additionalProperties"] = false,
            ["properties"] = new JsonObject
            {
                ["glob"] = StringField("Include glob — relative to the workspace root."),
                ["exclude"] = StringArrayField("Exclude globs — subtracted from the include set."),
                ["frontmatter_must_have"] = StringArrayField(
                    "Frontmatter keys that must be present for a file to match."
                ),
            },
        };

    private static JsonObject SlugSchema() =>
        new()
        {
            ["type"] = "object",
            ["additionalProperties"] = false,
            ["properties"] = new JsonObject
            {
                ["from"] = new JsonObject
                {
                    ["type"] = "string",
                    ["enum"] = new JsonArray { "filename", "path", "frontmatter", "template" },
                    ["default"] = "filename",
                },
                ["transform"] = new JsonObject
                {
                    ["type"] = "string",
                    ["enum"] = new JsonArray { "as-is", "kebab", "snake", "lower" },
                    ["default"] = "as-is",
                },
                ["template"] = StringField(
                    "Interpolation pattern when from=template (`{filename}`, `{parent_dir}`, `{path}`, `{extension}`)."
                ),
            },
        };

    private static JsonObject MetadataSchema(JsonArray accessorEnum) =>
        new()
        {
            ["type"] = "object",
            ["additionalProperties"] = false,
            ["properties"] = new JsonObject
            {
                ["source"] = new JsonObject
                {
                    ["type"] = "string",
                    ["enum"] = new JsonArray { "frontmatter", "none" },
                    ["default"] = "frontmatter",
                },
                ["computed"] = new JsonObject
                {
                    ["type"] = "object",
                    ["description"] =
                        "Map of output property name → accessor (e.g. `mtime: file.mtime`).",
                    ["additionalProperties"] = new JsonObject
                    {
                        ["type"] = "string",
                        ["enum"] = accessorEnum,
                    },
                },
                ["required"] = StringArrayField(
                    "Frontmatter keys whose absence flags the entity as a schema failure."
                ),
            },
        };

    private static JsonObject RelationshipSchema(JsonArray targetKindEnum)
    {
        // target_kind accepts: "any", a single kind id, or an array of kind ids.
        var targetKindString = new JsonObject { ["type"] = "string", ["enum"] = targetKindEnum };
        var targetKindArray = new JsonObject
        {
            ["type"] = "array",
            ["items"] = new JsonObject
            {
                ["type"] = "string",
                ["enum"] = targetKindEnum.DeepClone(),
            },
        };

        // source accepts: shorthand string ("frontmatter.related" / "glob:**" / "body.links") or
        // structured object {kind, key, literals}.
        var sourceString = new JsonObject
        {
            ["type"] = "string",
            ["description"] =
                "Shorthand: `frontmatter.<key>` / `glob:<pattern>` / `path-template:<tpl>` / `body.links`.",
        };
        var sourceObject = new JsonObject
        {
            ["type"] = "object",
            ["required"] = new JsonArray { "kind" },
            ["additionalProperties"] = false,
            ["properties"] = new JsonObject
            {
                ["kind"] = new JsonObject
                {
                    ["type"] = "string",
                    ["enum"] = new JsonArray
                    {
                        "frontmatter",
                        "path-template",
                        "glob",
                        "literal",
                        "body-links",
                        "body-code-refs",
                    },
                },
                ["key"] = StringField(
                    "Frontmatter key, glob pattern, or path template — depends on `kind`."
                ),
                ["literals"] = StringArrayField("Static value list when `kind: literal`."),
            },
        };

        var filterObject = new JsonObject
        {
            ["type"] = "object",
            ["required"] = new JsonArray { "kind", "pattern" },
            ["additionalProperties"] = false,
            ["properties"] = new JsonObject
            {
                ["kind"] = new JsonObject
                {
                    ["type"] = "string",
                    ["enum"] = new JsonArray { "glob", "regex", "type" },
                },
                ["pattern"] = StringField(
                    "Glob expression, regex, or one of {path, glob, url, slug} when kind=type. Prefix with `!` to negate (glob only)."
                ),
            },
        };

        return new JsonObject
        {
            ["type"] = "object",
            ["required"] = new JsonArray { "kind" },
            ["additionalProperties"] = false,
            ["properties"] = new JsonObject
            {
                ["kind"] = new JsonObject
                {
                    ["type"] = "string",
                    ["pattern"] = "^[a-z][a-z0-9_]*$",
                    ["description"] =
                        "Machine-readable edge label; written to entity_refs.relationship.",
                },
                ["name"] = StringField(
                    "CDFS folder display name. Loader humanizes from kind when omitted."
                ),
                ["icon"] = StringField("Icon key for the CDFS folder."),
                ["description"] = StringField("Tooltip / docs string."),
                ["order"] = new JsonObject
                {
                    ["type"] = "integer",
                    ["default"] = 100,
                    ["description"] = "CDFS folder sort order; lower comes first.",
                },
                ["source"] = new JsonObject
                {
                    ["oneOf"] = new JsonArray { sourceString, sourceObject },
                },
                ["filter"] = filterObject,
                ["interpret"] = new JsonObject
                {
                    ["type"] = "string",
                    ["enum"] = new JsonArray
                    {
                        "auto",
                        "path",
                        "slug",
                        "glob",
                        "url",
                        "ref-object",
                    },
                    ["default"] = "auto",
                    ["description"] = "How each consumed value is interpreted into a target.",
                },
                // Legacy resolution shorthands — accepted by the loader but discouraged for new conventions.
                ["select_path"] = StringField(
                    "Legacy: path-template resolution. Use `source: path-template:…` in new conventions."
                ),
                ["select_frontmatter"] = StringField(
                    "Legacy: frontmatter slug resolution. Use `source: frontmatter.<key>` in new conventions."
                ),
                ["target_kind"] = new JsonObject
                {
                    ["oneOf"] = new JsonArray { targetKindString, targetKindArray },
                    ["description"] =
                        "Entity kind(s) to resolve against. `any` means kind-agnostic.",
                },
                ["metadata"] = new JsonObject
                {
                    ["type"] = "object",
                    ["description"] =
                        "Per-edge metadata template merged into entity_refs.metadata. Supports `${value}` substitution.",
                    ["additionalProperties"] = new JsonObject { ["type"] = "string" },
                },
                ["inverse"] = StringField(
                    "Reverse edge label — auto-creates a mirrored ref. Set to the same value as kind for symmetric edges."
                ),
                ["inverse_name"] = StringField(
                    "CDFS folder name for the reverse edge. Defaults to name (symmetric) or humanized inverse kind."
                ),
                ["inverse_icon"] = StringField("Icon for the reverse-edge folder."),
            },
        };
    }

    private static JsonObject ActionSchema() =>
        new()
        {
            ["type"] = "object",
            ["required"] = new JsonArray { "id", "runs" },
            ["additionalProperties"] = false,
            ["properties"] = new JsonObject
            {
                ["id"] = StringField("Action id; stable for telemetry."),
                ["label"] = StringField("Menu-item label. Defaults to id."),
                ["icon"] = StringField("Optional icon key."),
                ["when"] = StringField("Visibility expression (literal equality only in v0.1.x)."),
                ["confirm"] = new JsonObject
                {
                    ["type"] = "string",
                    ["enum"] = new JsonArray { "required" },
                },
                ["runs"] = new JsonObject
                {
                    ["type"] = "object",
                    ["required"] = new JsonArray { "kind" },
                    ["additionalProperties"] = false,
                    ["properties"] = new JsonObject
                    {
                        ["kind"] = new JsonObject
                        {
                            ["type"] = "string",
                            ["enum"] = new JsonArray
                            {
                                "file-mutate",
                                "agent-prompt",
                                "query",
                                "job",
                            },
                        },
                        ["script"] = StringField("Job-script slug for kind=file-mutate."),
                        ["prompt"] = StringField("Templated prompt for kind=agent-prompt."),
                        ["tool"] = StringField("Projection tool name for kind=query."),
                        ["args"] = new JsonObject
                        {
                            ["type"] = "object",
                            ["additionalProperties"] = new JsonObject { ["type"] = "string" },
                        },
                        ["job_id"] = StringField("Workspace job id for kind=job."),
                        ["output"] = new JsonObject
                        {
                            ["type"] = "object",
                            ["required"] = new JsonArray { "target" },
                            ["additionalProperties"] = false,
                            ["properties"] = new JsonObject
                            {
                                ["target"] = StringField(
                                    "Where output lands: `frontmatter.<key>` / `body` / `comments`."
                                ),
                            },
                        },
                    },
                },
            },
        };

    private static JsonObject StringField(string description) =>
        new() { ["type"] = "string", ["description"] = description };

    private static JsonObject StringArrayField(string description) =>
        new()
        {
            ["type"] = "array",
            ["description"] = description,
            ["items"] = new JsonObject { ["type"] = "string" },
        };
}
