// This file is auto-generated by @hey-api/openapi-ts

export const AgentChatRequestSchema = {
  required: ['message'],
  type: 'object',
  properties: {
    message: {
      type: 'string',
    },
    history: {
      type: ['null', 'array'],
      items: {
        $ref: '#/components/schemas/ChatTurn',
      },
    },
    provider: {
      type: ['null', 'string'],
    },
    currentScreen: {
      type: ['null', 'string'],
    },
  },
} as const;

export const AgentChatResultSchema = {
  required: ['ok', 'reply', 'provider', 'model', 'latencyMs', 'error'],
  type: 'object',
  properties: {
    ok: {
      type: 'boolean',
    },
    reply: {
      type: 'string',
    },
    provider: {
      type: ['null', 'string'],
    },
    model: {
      type: ['null', 'string'],
    },
    latencyMs: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['null', 'integer', 'string'],
      format: 'int64',
    },
    error: {
      type: ['null', 'string'],
    },
  },
} as const;

export const AgentHealthResultSchema = {
  required: ['ok', 'provider', 'model', 'latencyMs', 'reply', 'error'],
  type: 'object',
  properties: {
    ok: {
      type: 'boolean',
    },
    provider: {
      type: ['null', 'string'],
    },
    model: {
      type: ['null', 'string'],
    },
    latencyMs: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['null', 'integer', 'string'],
      format: 'int64',
    },
    reply: {
      type: ['null', 'string'],
    },
    error: {
      type: ['null', 'string'],
    },
  },
} as const;

export const AiProvidersConfigSchema = {
  type: 'object',
  properties: {
    defaultProvider: {
      type: ['null', 'string'],
    },
    anthropic: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/AnthropicConfig',
        },
      ],
    },
    openAI: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/OpenAIConfig',
        },
      ],
    },
    local: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/LocalProviderConfig',
        },
      ],
    },
  },
} as const;

export const AnthropicConfigSchema = {
  type: 'object',
  properties: {
    apiKeySecret: {
      type: ['null', 'string'],
    },
    defaultModel: {
      type: ['null', 'string'],
    },
    baseUrl: {
      type: ['null', 'string'],
    },
  },
} as const;

export const ApiResultOfAgentChatResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/AgentChatResult',
        },
      ],
    },
  },
} as const;

export const ApiResultOfAgentHealthResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/AgentHealthResult',
        },
      ],
    },
  },
} as const;

export const ApiResultOfbooleanSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      type: 'boolean',
    },
  },
} as const;

export const ApiResultOfBrandingAssetResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/BrandingAssetResult',
        },
      ],
    },
  },
} as const;

export const ApiResultOfBrandingConfigSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/BrandingConfig',
        },
      ],
    },
  },
} as const;

export const ApiResultOfConventionsListResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/ConventionsListResult',
        },
      ],
    },
  },
} as const;

export const ApiResultOfCreateUserResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/CreateUserResult',
        },
      ],
    },
  },
} as const;

export const ApiResultOfEchoResponseSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/EchoResponse',
        },
      ],
    },
  },
} as const;

export const ApiResultOfEntityDetailSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/EntityDetail',
        },
      ],
    },
  },
} as const;

export const ApiResultOfEnvironmentConfigViewSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/EnvironmentConfigView',
        },
      ],
    },
  },
} as const;

export const ApiResultOfGuidSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      type: ['null', 'string'],
      format: 'uuid',
    },
  },
} as const;

export const ApiResultOfIReadOnlyListOfEntitySummarySchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      type: ['null', 'array'],
      items: {
        $ref: '#/components/schemas/EntitySummary',
      },
    },
  },
} as const;

export const ApiResultOfIReadOnlyListOfJobRunResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      type: ['null', 'array'],
      items: {
        $ref: '#/components/schemas/JobRunResult',
      },
    },
  },
} as const;

export const ApiResultOfIReadOnlyListOfJobScriptResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      type: ['null', 'array'],
      items: {
        $ref: '#/components/schemas/JobScriptResult',
      },
    },
  },
} as const;

export const ApiResultOfIReadOnlyListOfPlanSummarySchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      type: ['null', 'array'],
      items: {
        $ref: '#/components/schemas/PlanSummary',
      },
    },
  },
} as const;

export const ApiResultOfIReadOnlyListOfScheduleResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      type: ['null', 'array'],
      items: {
        $ref: '#/components/schemas/ScheduleResult',
      },
    },
  },
} as const;

export const ApiResultOfIReadOnlyListOfstringSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      type: ['null', 'array'],
      items: {
        type: 'string',
      },
    },
  },
} as const;

export const ApiResultOfIReadOnlyListOfToolEntrySchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      type: ['null', 'array'],
      items: {
        $ref: '#/components/schemas/ToolEntry',
      },
    },
  },
} as const;

export const ApiResultOfIReadOnlyListOfUserResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      type: ['null', 'array'],
      items: {
        $ref: '#/components/schemas/UserResult',
      },
    },
  },
} as const;

export const ApiResultOfIReadOnlyListOfWorkspaceResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      type: ['null', 'array'],
      items: {
        $ref: '#/components/schemas/WorkspaceResult',
      },
    },
  },
} as const;

export const ApiResultOfJobRunDetailResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/JobRunDetailResult',
        },
      ],
    },
  },
} as const;

export const ApiResultOfJobRunResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/JobRunResult',
        },
      ],
    },
  },
} as const;

export const ApiResultOfJobScriptResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/JobScriptResult',
        },
      ],
    },
  },
} as const;

export const ApiResultOfPingResponseSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/PingResponse',
        },
      ],
    },
  },
} as const;

export const ApiResultOfPlanDetailSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/PlanDetail',
        },
      ],
    },
  },
} as const;

export const ApiResultOfScheduleResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/ScheduleResult',
        },
      ],
    },
  },
} as const;

export const ApiResultOfSyncProjectionResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/SyncProjectionResult',
        },
      ],
    },
  },
} as const;

export const ApiResultOfUserResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/UserResult',
        },
      ],
    },
  },
} as const;

export const ApiResultOfWorkspaceConnectionTestResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/WorkspaceConnectionTestResult',
        },
      ],
    },
  },
} as const;

export const ApiResultOfWorkspacePluginsResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/WorkspacePluginsResult',
        },
      ],
    },
  },
} as const;

export const ApiResultOfWorkspaceResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/WorkspaceResult',
        },
      ],
    },
  },
} as const;

export const ApiResultOfWorkspaceSyncResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/WorkspaceSyncResult',
        },
      ],
    },
  },
} as const;

export const BrandingAssetResultSchema = {
  required: ['url', 'contentType', 'size'],
  type: 'object',
  properties: {
    url: {
      type: 'string',
    },
    contentType: {
      type: 'string',
    },
    size: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int64',
    },
  },
} as const;

export const BrandingConfigSchema = {
  required: [
    'productName',
    'logoUrl',
    'faviconUrl',
    'loginBackgroundUrl',
    'loginTagline',
    'mode',
    'palette',
    'chrome',
    'chromeLight',
    'fontFamily',
    'fontFamilyMono',
    'customCss',
    'footerText',
    'supportEmail',
  ],
  type: 'object',
  properties: {
    productName: {
      type: 'string',
    },
    logoUrl: {
      type: ['null', 'string'],
    },
    faviconUrl: {
      type: ['null', 'string'],
    },
    loginBackgroundUrl: {
      type: ['null', 'string'],
    },
    loginTagline: {
      type: ['null', 'string'],
    },
    mode: {
      type: 'string',
    },
    palette: {
      $ref: '#/components/schemas/BrandPalette',
    },
    chrome: {
      $ref: '#/components/schemas/ChromeTokens',
    },
    chromeLight: {
      $ref: '#/components/schemas/ChromeTokens',
    },
    fontFamily: {
      type: ['null', 'string'],
    },
    fontFamilyMono: {
      type: ['null', 'string'],
    },
    customCss: {
      type: ['null', 'string'],
    },
    footerText: {
      type: ['null', 'string'],
    },
    supportEmail: {
      type: ['null', 'string'],
    },
  },
} as const;

export const BrandPaletteSchema = {
  type: 'object',
  properties: {
    primary: {
      type: ['null', 'string'],
    },
    secondary: {
      type: ['null', 'string'],
    },
    accent: {
      type: ['null', 'string'],
    },
    positive: {
      type: ['null', 'string'],
    },
    negative: {
      type: ['null', 'string'],
    },
    info: {
      type: ['null', 'string'],
    },
    warning: {
      type: ['null', 'string'],
    },
    dark: {
      type: ['null', 'string'],
    },
    darkPage: {
      type: ['null', 'string'],
    },
  },
} as const;

export const ChangePasswordRequestSchema = {
  required: ['currentPassword', 'newPassword', 'confirmPassword'],
  type: 'object',
  properties: {
    currentPassword: {
      type: 'string',
    },
    newPassword: {
      type: 'string',
    },
    confirmPassword: {
      type: 'string',
    },
  },
} as const;

export const ChatTurnSchema = {
  required: ['role', 'content'],
  type: 'object',
  properties: {
    role: {
      type: 'string',
    },
    content: {
      type: 'string',
    },
  },
} as const;

export const ChromeTokensSchema = {
  type: 'object',
  properties: {
    bgPage: {
      type: ['null', 'string'],
    },
    bgSurface: {
      type: ['null', 'string'],
    },
    bgHeader: {
      type: ['null', 'string'],
    },
    bgSidebar: {
      type: ['null', 'string'],
    },
    bgElevated: {
      type: ['null', 'string'],
    },
    fgPrimary: {
      type: ['null', 'string'],
    },
    fgSecondary: {
      type: ['null', 'string'],
    },
    fgTertiary: {
      type: ['null', 'string'],
    },
    borderSubtle: {
      type: ['null', 'string'],
    },
    borderDefault: {
      type: ['null', 'string'],
    },
    borderStrong: {
      type: ['null', 'string'],
    },
  },
} as const;

export const ConventionLoadErrorSchema = {
  required: ['source', 'message'],
  type: 'object',
  properties: {
    source: {
      type: ['null', 'string'],
    },
    message: {
      type: 'string',
    },
  },
} as const;

export const ConventionsListResultSchema = {
  required: ['conventions', 'errors'],
  type: 'object',
  properties: {
    conventions: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/ConventionSummary',
      },
    },
    errors: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/ConventionLoadError',
      },
    },
  },
} as const;

export const ConventionSummarySchema = {
  required: ['id', 'description', 'priority', 'glob', 'extends', 'contentHash', 'sourcePath'],
  type: 'object',
  properties: {
    id: {
      type: 'string',
    },
    description: {
      type: ['null', 'string'],
    },
    priority: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int32',
    },
    glob: {
      type: 'string',
    },
    extends: {
      type: ['null', 'string'],
    },
    contentHash: {
      type: 'string',
    },
    sourcePath: {
      type: ['null', 'string'],
    },
  },
} as const;

export const CreateJobScriptRequestSchema = {
  required: ['slug', 'name', 'description', 'pattern', 'frontmatter', 'body', 'status'],
  type: 'object',
  properties: {
    slug: {
      type: 'string',
    },
    name: {
      type: 'string',
    },
    description: {
      type: ['null', 'string'],
    },
    pattern: {
      type: 'string',
    },
    frontmatter: {
      type: 'string',
    },
    body: {
      type: 'string',
    },
    status: {
      type: 'string',
    },
  },
} as const;

export const CreateScheduleRequestSchema = {
  required: ['jobScriptId', 'kind', 'cronExpression', 'enabled'],
  type: 'object',
  properties: {
    jobScriptId: {
      type: 'string',
      format: 'uuid',
    },
    kind: {
      type: 'string',
    },
    cronExpression: {
      type: ['null', 'string'],
    },
    enabled: {
      type: 'boolean',
    },
  },
} as const;

export const CreateUserRequestSchema = {
  required: ['email', 'displayName', 'role', 'temporaryPassword'],
  type: 'object',
  properties: {
    email: {
      type: 'string',
    },
    displayName: {
      type: 'string',
    },
    role: {
      type: 'string',
    },
    temporaryPassword: {
      type: ['null', 'string'],
    },
  },
} as const;

export const CreateUserResultSchema = {
  required: ['userId', 'email', 'displayName', 'role', 'temporaryPassword'],
  type: 'object',
  properties: {
    userId: {
      type: 'string',
      format: 'uuid',
    },
    email: {
      type: 'string',
    },
    displayName: {
      type: 'string',
    },
    role: {
      type: 'string',
    },
    temporaryPassword: {
      type: 'string',
    },
  },
} as const;

export const CreateWorkspaceRequestSchema = {
  required: ['slug', 'name', 'description', 'type'],
  type: 'object',
  properties: {
    slug: {
      type: 'string',
    },
    name: {
      type: 'string',
    },
    description: {
      type: ['null', 'string'],
    },
    type: {
      type: 'string',
    },
    gitSettings: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/GitWorkspaceSettingsDto',
        },
      ],
    },
    localSettings: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/LocalWorkspaceSettingsDto',
        },
      ],
    },
  },
} as const;

export const EchoRequestSchema = {
  required: ['message', 'repeat'],
  type: 'object',
  properties: {
    message: {
      type: 'string',
    },
    repeat: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['null', 'integer', 'string'],
      format: 'int32',
    },
  },
} as const;

export const EchoResponseSchema = {
  required: ['message'],
  type: 'object',
  properties: {
    message: {
      type: 'string',
    },
  },
} as const;

export const EntityDetailSchema = {
  required: [
    'id',
    'kind',
    'slug',
    'path',
    'conventionId',
    'metadataJson',
    'contentHash',
    'lastSeenAt',
    'refsOut',
    'refsIn',
  ],
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    kind: {
      type: 'string',
    },
    slug: {
      type: 'string',
    },
    path: {
      type: 'string',
    },
    conventionId: {
      type: 'string',
    },
    metadataJson: {
      type: 'string',
    },
    contentHash: {
      type: 'string',
    },
    lastSeenAt: {
      type: 'string',
      format: 'date-time',
    },
    refsOut: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/EntityRefSummary',
      },
    },
    refsIn: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/EntityRefSummary',
      },
    },
  },
} as const;

export const EntityRefSummarySchema = {
  required: ['id', 'toEntityId', 'relationship', 'targetKind', 'targetSlug'],
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    toEntityId: {
      type: ['null', 'string'],
      format: 'uuid',
    },
    relationship: {
      type: 'string',
    },
    targetKind: {
      type: ['null', 'string'],
    },
    targetSlug: {
      type: ['null', 'string'],
    },
  },
} as const;

export const EntitySummarySchema = {
  required: ['id', 'kind', 'slug', 'path', 'conventionId', 'contentHash'],
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    kind: {
      type: 'string',
    },
    slug: {
      type: 'string',
    },
    path: {
      type: 'string',
    },
    conventionId: {
      type: 'string',
    },
    contentHash: {
      type: 'string',
    },
  },
} as const;

export const EnvironmentConfigSchema = {
  required: ['general', 'smtp', 'aiProviders'],
  type: 'object',
  properties: {
    general: {
      $ref: '#/components/schemas/GeneralConfig',
    },
    smtp: {
      $ref: '#/components/schemas/SmtpConfig',
    },
    aiProviders: {
      $ref: '#/components/schemas/AiProvidersConfig',
    },
  },
} as const;

export const EnvironmentConfigViewSchema = {
  required: ['config', 'secretsPresent'],
  type: 'object',
  properties: {
    config: {
      $ref: '#/components/schemas/EnvironmentConfig',
    },
    secretsPresent: {
      type: 'object',
      additionalProperties: {
        type: 'boolean',
      },
    },
  },
} as const;

export const GeneralConfigSchema = {
  type: 'object',
  properties: {
    baseUrl: {
      type: ['null', 'string'],
    },
    timezone: {
      type: ['null', 'string'],
    },
  },
} as const;

export const GitWorkspaceSettingsDtoSchema = {
  required: ['repositoryUrl'],
  type: 'object',
  properties: {
    repositoryUrl: {
      type: 'string',
    },
    authMode: {
      type: 'string',
      default: 'none',
    },
    authSecret: {
      type: ['null', 'string'],
    },
    authCredential: {
      type: ['null', 'string'],
    },
    workingBranch: {
      type: 'string',
      default: 'creuser/main',
    },
    sourceBranch: {
      type: 'string',
      default: 'main',
    },
    mode: {
      type: 'string',
      default: 'direct-push',
    },
    pushFrequency: {
      type: 'string',
      default: 'every-commit',
    },
  },
} as const;

export const IFormFileSchema = {
  type: 'string',
  format: 'binary',
} as const;

export const JobRunDetailResultSchema = {
  required: ['run', 'steps'],
  type: 'object',
  properties: {
    run: {
      $ref: '#/components/schemas/JobRunResult',
    },
    steps: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/JobRunStepResult',
      },
    },
  },
} as const;

export const JobRunResultSchema = {
  required: [
    'runId',
    'jobScriptId',
    'workspaceId',
    'status',
    'triggerKind',
    'startedAt',
    'completedAt',
    'durationMs',
    'totalTokensUsed',
    'totalCostUsd',
    'failureMessage',
    'startCommitSha',
    'endCommitSha',
  ],
  type: 'object',
  properties: {
    runId: {
      type: 'string',
      format: 'uuid',
    },
    jobScriptId: {
      type: 'string',
      format: 'uuid',
    },
    workspaceId: {
      type: 'string',
      format: 'uuid',
    },
    status: {
      type: 'string',
    },
    triggerKind: {
      type: 'string',
    },
    startedAt: {
      type: 'string',
      format: 'date-time',
    },
    completedAt: {
      type: ['null', 'string'],
      format: 'date-time',
    },
    durationMs: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int64',
    },
    totalTokensUsed: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['null', 'integer', 'string'],
      format: 'int64',
    },
    totalCostUsd: {
      pattern: '^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$',
      type: ['null', 'number', 'string'],
      format: 'double',
    },
    failureMessage: {
      type: ['null', 'string'],
    },
    startCommitSha: {
      type: ['null', 'string'],
    },
    endCommitSha: {
      type: ['null', 'string'],
    },
    planId: {
      type: ['null', 'string'],
      format: 'uuid',
    },
  },
} as const;

export const JobRunStepResultSchema = {
  required: [
    'stepId',
    'position',
    'stepType',
    'name',
    'status',
    'idempotencyKey',
    'cachedFromStepId',
    'inputsJson',
    'outputsJson',
    'fileChangeCount',
    'commitSha',
    'startedAt',
    'completedAt',
    'durationMs',
    'tokensUsed',
    'costUsd',
    'errorMessage',
  ],
  type: 'object',
  properties: {
    stepId: {
      type: 'string',
      format: 'uuid',
    },
    position: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int32',
    },
    stepType: {
      type: 'string',
    },
    name: {
      type: 'string',
    },
    status: {
      type: 'string',
    },
    idempotencyKey: {
      type: 'string',
    },
    cachedFromStepId: {
      type: ['null', 'string'],
      format: 'uuid',
    },
    inputsJson: {
      type: 'string',
    },
    outputsJson: {
      type: ['null', 'string'],
    },
    fileChangeCount: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int32',
    },
    commitSha: {
      type: ['null', 'string'],
    },
    startedAt: {
      type: 'string',
      format: 'date-time',
    },
    completedAt: {
      type: ['null', 'string'],
      format: 'date-time',
    },
    durationMs: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int64',
    },
    tokensUsed: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['null', 'integer', 'string'],
      format: 'int64',
    },
    costUsd: {
      pattern: '^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$',
      type: ['null', 'number', 'string'],
      format: 'double',
    },
    errorMessage: {
      type: ['null', 'string'],
    },
  },
} as const;

export const JobScriptResultSchema = {
  required: [
    'jobScriptId',
    'workspaceId',
    'slug',
    'name',
    'description',
    'pattern',
    'frontmatter',
    'body',
    'status',
    'createdAt',
    'updatedAt',
  ],
  type: 'object',
  properties: {
    jobScriptId: {
      type: 'string',
      format: 'uuid',
    },
    workspaceId: {
      type: 'string',
      format: 'uuid',
    },
    slug: {
      type: 'string',
    },
    name: {
      type: 'string',
    },
    description: {
      type: ['null', 'string'],
    },
    pattern: {
      type: 'string',
    },
    frontmatter: {
      type: 'string',
    },
    body: {
      type: 'string',
    },
    status: {
      type: 'string',
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
    },
    updatedAt: {
      type: 'string',
      format: 'date-time',
    },
  },
} as const;

export const LocalProviderConfigSchema = {
  type: 'object',
  properties: {
    baseUrl: {
      type: ['null', 'string'],
    },
    defaultModel: {
      type: ['null', 'string'],
    },
    apiKeySecret: {
      type: ['null', 'string'],
    },
    kind: {
      type: ['null', 'string'],
    },
  },
} as const;

export const LocalWorkspaceSettingsDtoSchema = {
  required: ['path'],
  type: 'object',
  properties: {
    path: {
      type: 'string',
    },
    writable: {
      type: 'boolean',
      default: true,
    },
  },
} as const;

export const LoginRequestSchema = {
  required: ['email', 'password'],
  type: 'object',
  properties: {
    email: {
      type: 'string',
    },
    password: {
      type: 'string',
    },
  },
} as const;

export const OpenAIConfigSchema = {
  type: 'object',
  properties: {
    apiKeySecret: {
      type: ['null', 'string'],
    },
    defaultModel: {
      type: ['null', 'string'],
    },
    baseUrl: {
      type: ['null', 'string'],
    },
    azureDeployment: {
      type: ['null', 'string'],
    },
  },
} as const;

export const PingResponseSchema = {
  required: ['message', 'serverTime'],
  type: 'object',
  properties: {
    message: {
      type: 'string',
    },
    serverTime: {
      type: 'string',
      format: 'date-time',
    },
  },
} as const;

export const PlanDetailSchema = {
  required: [
    'id',
    'workspaceId',
    'jobScriptId',
    'goal',
    'stepsJson',
    'reasoning',
    'model',
    'provider',
    'tokensUsed',
    'createdAt',
  ],
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    workspaceId: {
      type: 'string',
      format: 'uuid',
    },
    jobScriptId: {
      type: 'string',
      format: 'uuid',
    },
    goal: {
      type: 'string',
    },
    stepsJson: {
      type: 'string',
    },
    reasoning: {
      type: ['null', 'string'],
    },
    model: {
      type: 'string',
    },
    provider: {
      type: 'string',
    },
    tokensUsed: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['null', 'integer', 'string'],
      format: 'int64',
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
    },
  },
} as const;

export const PlanSummarySchema = {
  required: [
    'id',
    'workspaceId',
    'jobScriptId',
    'goal',
    'stepCount',
    'reasoning',
    'model',
    'provider',
    'tokensUsed',
    'createdAt',
  ],
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    workspaceId: {
      type: 'string',
      format: 'uuid',
    },
    jobScriptId: {
      type: 'string',
      format: 'uuid',
    },
    goal: {
      type: 'string',
    },
    stepCount: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int32',
    },
    reasoning: {
      type: ['null', 'string'],
    },
    model: {
      type: 'string',
    },
    provider: {
      type: 'string',
    },
    tokensUsed: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['null', 'integer', 'string'],
      format: 'int64',
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
    },
  },
} as const;

export const ProjectionReportSchema = {
  required: [
    'syncedAt',
    'scanDurationMs',
    'conventionCount',
    'entitiesByKind',
    'entityTotal',
    'refsResolved',
    'refsUnresolved',
    'schemaFailures',
    'conventionConflicts',
    'conventionVersions',
  ],
  type: 'object',
  properties: {
    syncedAt: {
      type: 'string',
      format: 'date-time',
    },
    scanDurationMs: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int64',
    },
    conventionCount: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int32',
    },
    entitiesByKind: {
      type: 'object',
      additionalProperties: {
        pattern: '^-?(?:0|[1-9]\\d*)$',
        type: ['integer', 'string'],
        format: 'int32',
      },
    },
    entityTotal: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int32',
    },
    refsResolved: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int32',
    },
    refsUnresolved: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int32',
    },
    schemaFailures: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int32',
    },
    conventionConflicts: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int32',
    },
    conventionVersions: {
      type: 'object',
      additionalProperties: {
        type: 'string',
      },
    },
  },
} as const;

export const ResetPasswordRequestSchema = {
  type: 'object',
  properties: {
    temporaryPassword: {
      type: ['null', 'string'],
    },
  },
} as const;

export const RunJobScriptRequestSchema = {
  required: ['parameters'],
  type: 'object',
  properties: {
    parameters: {
      type: ['null', 'object'],
    },
  },
} as const;

export const ScheduleResultSchema = {
  required: [
    'scheduleId',
    'workspaceId',
    'jobScriptId',
    'jobName',
    'kind',
    'cronExpression',
    'enabled',
    'nextDueAt',
    'lastFiredAt',
    'lastRunId',
    'createdAt',
  ],
  type: 'object',
  properties: {
    scheduleId: {
      type: 'string',
      format: 'uuid',
    },
    workspaceId: {
      type: 'string',
      format: 'uuid',
    },
    jobScriptId: {
      type: 'string',
      format: 'uuid',
    },
    jobName: {
      type: 'string',
    },
    kind: {
      type: 'string',
    },
    cronExpression: {
      type: ['null', 'string'],
    },
    enabled: {
      type: 'boolean',
    },
    nextDueAt: {
      type: ['null', 'string'],
      format: 'date-time',
    },
    lastFiredAt: {
      type: ['null', 'string'],
      format: 'date-time',
    },
    lastRunId: {
      type: ['null', 'string'],
      format: 'uuid',
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
    },
  },
} as const;

export const SetActiveRequestSchema = {
  required: ['isActive'],
  type: 'object',
  properties: {
    isActive: {
      type: 'boolean',
    },
  },
} as const;

export const SetSecretRequestSchema = {
  required: ['value'],
  type: 'object',
  properties: {
    value: {
      type: 'string',
    },
  },
} as const;

export const SetUserRoleRequestSchema = {
  required: ['role'],
  type: 'object',
  properties: {
    role: {
      type: 'string',
    },
  },
} as const;

export const SmtpConfigSchema = {
  type: 'object',
  properties: {
    host: {
      type: ['null', 'string'],
    },
    port: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['null', 'integer', 'string'],
      format: 'int32',
    },
    username: {
      type: ['null', 'string'],
    },
    passwordSecret: {
      type: ['null', 'string'],
    },
    encryption: {
      type: ['null', 'string'],
    },
    fromAddress: {
      type: ['null', 'string'],
    },
    fromName: {
      type: ['null', 'string'],
    },
  },
} as const;

export const SyncProjectionResultSchema = {
  required: ['report'],
  type: 'object',
  properties: {
    report: {
      $ref: '#/components/schemas/ProjectionReport',
    },
  },
} as const;

export const TestWorkspaceConnectionRequestSchema = {
  required: ['type'],
  type: 'object',
  properties: {
    type: {
      type: 'string',
    },
    gitSettings: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/GitWorkspaceSettingsDto',
        },
      ],
    },
    localSettings: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/LocalWorkspaceSettingsDto',
        },
      ],
    },
  },
} as const;

export const ToolEntrySchema = {
  required: ['name', 'category', 'description', 'source'],
  type: 'object',
  properties: {
    name: {
      type: 'string',
    },
    category: {
      type: 'string',
    },
    description: {
      type: ['null', 'string'],
    },
    source: {
      type: 'string',
    },
  },
} as const;

export const UpdateJobScriptRequestSchema = {
  required: ['name', 'description', 'pattern', 'frontmatter', 'body', 'status'],
  type: 'object',
  properties: {
    name: {
      type: 'string',
    },
    description: {
      type: ['null', 'string'],
    },
    pattern: {
      type: 'string',
    },
    frontmatter: {
      type: 'string',
    },
    body: {
      type: 'string',
    },
    status: {
      type: 'string',
    },
  },
} as const;

export const UpdateScheduleRequestSchema = {
  required: ['kind', 'cronExpression', 'enabled'],
  type: 'object',
  properties: {
    kind: {
      type: 'string',
    },
    cronExpression: {
      type: ['null', 'string'],
    },
    enabled: {
      type: 'boolean',
    },
  },
} as const;

export const UpdateWorkspaceRequestSchema = {
  required: ['name', 'description', 'type'],
  type: 'object',
  properties: {
    name: {
      type: 'string',
    },
    description: {
      type: ['null', 'string'],
    },
    type: {
      type: 'string',
    },
    gitSettings: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/GitWorkspaceSettingsDto',
        },
      ],
    },
    localSettings: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/LocalWorkspaceSettingsDto',
        },
      ],
    },
  },
} as const;

export const UserResultSchema = {
  required: [
    'userId',
    'email',
    'displayName',
    'role',
    'isActive',
    'mustChangePassword',
    'lastLoginAt',
  ],
  type: 'object',
  properties: {
    userId: {
      type: 'string',
      format: 'uuid',
    },
    email: {
      type: 'string',
    },
    displayName: {
      type: 'string',
    },
    role: {
      type: 'string',
    },
    isActive: {
      type: 'boolean',
    },
    mustChangePassword: {
      type: 'boolean',
    },
    lastLoginAt: {
      type: ['null', 'string'],
      format: 'date-time',
    },
  },
} as const;

export const WorkspaceConnectionTestResultSchema = {
  required: ['ok', 'latencyMs', 'error'],
  type: 'object',
  properties: {
    ok: {
      type: 'boolean',
    },
    latencyMs: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int64',
    },
    error: {
      type: ['null', 'string'],
    },
  },
} as const;

export const WorkspacePluginInfoSchema = {
  required: [
    'pluginId',
    'name',
    'version',
    'author',
    'description',
    'enabled',
    'status',
    'statusMessage',
    'provides',
    'requiredTools',
    'loadedAt',
  ],
  type: 'object',
  properties: {
    pluginId: {
      type: 'string',
    },
    name: {
      type: 'string',
    },
    version: {
      type: 'string',
    },
    author: {
      type: ['null', 'string'],
    },
    description: {
      type: ['null', 'string'],
    },
    enabled: {
      type: 'boolean',
    },
    status: {
      type: 'string',
    },
    statusMessage: {
      type: ['null', 'string'],
    },
    provides: {
      type: 'array',
      items: {
        type: 'string',
      },
    },
    requiredTools: {
      type: 'array',
      items: {
        type: 'string',
      },
    },
    loadedAt: {
      type: ['null', 'string'],
      format: 'date-time',
    },
  },
} as const;

export const WorkspacePluginsResultSchema = {
  required: ['plugins', 'note'],
  type: 'object',
  properties: {
    plugins: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/WorkspacePluginInfo',
      },
    },
    note: {
      type: ['null', 'string'],
    },
  },
} as const;

export const WorkspaceResultSchema = {
  required: [
    'workspaceId',
    'slug',
    'name',
    'description',
    'type',
    'gitSettings',
    'localSettings',
    'authSecretPresent',
    'createdAt',
    'updatedAt',
    'lastSyncAt',
    'lastSyncSha',
    'lastSyncStatus',
    'lastSyncMessage',
  ],
  type: 'object',
  properties: {
    workspaceId: {
      type: 'string',
      format: 'uuid',
    },
    slug: {
      type: 'string',
    },
    name: {
      type: 'string',
    },
    description: {
      type: ['null', 'string'],
    },
    type: {
      type: 'string',
    },
    gitSettings: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/GitWorkspaceSettingsDto',
        },
      ],
    },
    localSettings: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/LocalWorkspaceSettingsDto',
        },
      ],
    },
    authSecretPresent: {
      type: 'boolean',
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
    },
    updatedAt: {
      type: 'string',
      format: 'date-time',
    },
    lastSyncAt: {
      type: ['null', 'string'],
      format: 'date-time',
    },
    lastSyncSha: {
      type: ['null', 'string'],
    },
    lastSyncStatus: {
      type: ['null', 'string'],
    },
    lastSyncMessage: {
      type: ['null', 'string'],
    },
  },
} as const;

export const WorkspaceSyncResultSchema = {
  required: ['ok', 'slug', 'sha', 'latencyMs', 'syncedAt', 'message', 'error'],
  type: 'object',
  properties: {
    ok: {
      type: 'boolean',
    },
    slug: {
      type: 'string',
    },
    sha: {
      type: ['null', 'string'],
    },
    latencyMs: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int64',
    },
    syncedAt: {
      type: 'string',
      format: 'date-time',
    },
    message: {
      type: ['null', 'string'],
    },
    error: {
      type: ['null', 'string'],
    },
    dirtyCount: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int32',
      default: 0,
    },
    requiresForce: {
      type: 'boolean',
      default: false,
    },
  },
} as const;
