// This file is auto-generated by @hey-api/openapi-ts

export const ApiResultOfbooleanSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      type: 'boolean',
    },
  },
} as const;

export const ApiResultOfCreateUserResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/CreateUserResult',
        },
      ],
    },
  },
} as const;

export const ApiResultOfEchoResponseSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/EchoResponse',
        },
      ],
    },
  },
} as const;

export const ApiResultOfIReadOnlyListOfUserResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      type: ['null', 'array'],
      items: {
        $ref: '#/components/schemas/UserResult',
      },
    },
  },
} as const;

export const ApiResultOfPingResponseSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/PingResponse',
        },
      ],
    },
  },
} as const;

export const ApiResultOfUserResultSchema = {
  required: ['result'],
  type: 'object',
  properties: {
    result: {
      oneOf: [
        {
          type: 'null',
        },
        {
          $ref: '#/components/schemas/UserResult',
        },
      ],
    },
  },
} as const;

export const ChangePasswordRequestSchema = {
  required: ['currentPassword', 'newPassword', 'confirmPassword'],
  type: 'object',
  properties: {
    currentPassword: {
      type: 'string',
    },
    newPassword: {
      type: 'string',
    },
    confirmPassword: {
      type: 'string',
    },
  },
} as const;

export const CreateUserRequestSchema = {
  required: ['email', 'displayName', 'role', 'temporaryPassword'],
  type: 'object',
  properties: {
    email: {
      type: 'string',
    },
    displayName: {
      type: 'string',
    },
    role: {
      type: 'string',
    },
    temporaryPassword: {
      type: ['null', 'string'],
    },
  },
} as const;

export const CreateUserResultSchema = {
  required: ['userId', 'email', 'displayName', 'role', 'temporaryPassword'],
  type: 'object',
  properties: {
    userId: {
      type: 'string',
      format: 'uuid',
    },
    email: {
      type: 'string',
    },
    displayName: {
      type: 'string',
    },
    role: {
      type: 'string',
    },
    temporaryPassword: {
      type: 'string',
    },
  },
} as const;

export const EchoRequestSchema = {
  required: ['message', 'repeat'],
  type: 'object',
  properties: {
    message: {
      type: 'string',
    },
    repeat: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['null', 'integer', 'string'],
      format: 'int32',
    },
  },
} as const;

export const EchoResponseSchema = {
  required: ['message'],
  type: 'object',
  properties: {
    message: {
      type: 'string',
    },
  },
} as const;

export const LoginRequestSchema = {
  required: ['email', 'password'],
  type: 'object',
  properties: {
    email: {
      type: 'string',
    },
    password: {
      type: 'string',
    },
  },
} as const;

export const PingResponseSchema = {
  required: ['message', 'serverTime'],
  type: 'object',
  properties: {
    message: {
      type: 'string',
    },
    serverTime: {
      type: 'string',
      format: 'date-time',
    },
  },
} as const;

export const SetActiveRequestSchema = {
  required: ['isActive'],
  type: 'object',
  properties: {
    isActive: {
      type: 'boolean',
    },
  },
} as const;

export const UserResultSchema = {
  required: ['userId', 'email', 'displayName', 'role', 'mustChangePassword'],
  type: 'object',
  properties: {
    userId: {
      type: 'string',
      format: 'uuid',
    },
    email: {
      type: 'string',
    },
    displayName: {
      type: 'string',
    },
    role: {
      type: 'string',
    },
    mustChangePassword: {
      type: 'boolean',
    },
  },
} as const;
