// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  ChangePasswordData,
  ChangePasswordResponses,
  CreateUserData,
  CreateUserResponses,
  EchoData,
  EchoResponses,
  GetCurrentUserData,
  GetCurrentUserResponses,
  ListUsersData,
  ListUsersResponses,
  LoginData,
  LoginResponses,
  LogoutData,
  LogoutResponses,
  PingData,
  PingResponses,
  ResetUserPasswordData,
  ResetUserPasswordResponses,
  SetUserActiveData,
  SetUserActiveResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class Auth {
  public static login<ThrowOnError extends boolean = false>(
    options: Options<LoginData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<LoginResponses, unknown, ThrowOnError>({
      url: '/api/auth/login',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static logout<ThrowOnError extends boolean = false>(
    options?: Options<LogoutData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
      url: '/api/auth/logout',
      ...options,
    });
  }

  public static getCurrentUser<ThrowOnError extends boolean = false>(
    options?: Options<GetCurrentUserData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<GetCurrentUserResponses, unknown, ThrowOnError>({
      url: '/api/auth/me',
      ...options,
    });
  }

  public static changePassword<ThrowOnError extends boolean = false>(
    options: Options<ChangePasswordData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<ChangePasswordResponses, unknown, ThrowOnError>({
      url: '/api/auth/change-password',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}

export class Admin {
  public static listUsers<ThrowOnError extends boolean = false>(
    options?: Options<ListUsersData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<ListUsersResponses, unknown, ThrowOnError>({
      url: '/api/admin/users',
      ...options,
    });
  }

  public static createUser<ThrowOnError extends boolean = false>(
    options: Options<CreateUserData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<CreateUserResponses, unknown, ThrowOnError>({
      url: '/api/admin/users',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static resetUserPassword<ThrowOnError extends boolean = false>(
    options: Options<ResetUserPasswordData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<ResetUserPasswordResponses, unknown, ThrowOnError>({
      url: '/api/admin/users/{id}/reset-password',
      ...options,
    });
  }

  public static setUserActive<ThrowOnError extends boolean = false>(
    options: Options<SetUserActiveData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<SetUserActiveResponses, unknown, ThrowOnError>({
      url: '/api/admin/users/{id}/active',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}

export class Diagnostics {
  /**
   * Liveness probe
   *
   * Returns a small payload echoing the server's wall-clock time. Used by the SPA and external monitors to confirm the API is reachable through the dev proxy and reverse proxies.
   */
  public static ping<ThrowOnError extends boolean = false>(
    options?: Options<PingData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<PingResponses, unknown, ThrowOnError>({
      url: '/api/ping',
      ...options,
    });
  }

  /**
   * Echo a message back, optionally repeated
   *
   * Demonstrates the full request/validation/envelope/ProblemDetails chain. Provided as a smoke-test endpoint for the dev proxy and the generated TypeScript client.
   */
  public static echo<ThrowOnError extends boolean = false>(
    options: Options<EchoData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<EchoResponses, unknown, ThrowOnError>({
      url: '/api/echo',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}
