// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from './client';
import { client } from './client.gen';
import type {
  AgentChatData,
  AgentChatResponses,
  ChangePasswordData,
  ChangePasswordResponses,
  CheckAgentHealthData,
  CheckAgentHealthResponses,
  CreateJobData,
  CreateJobResponses,
  CreateUserData,
  CreateUserResponses,
  CreateWorkspaceData,
  CreateWorkspaceResponses,
  DeleteEnvironmentSecretData,
  DeleteEnvironmentSecretResponses,
  DeleteJobData,
  DeleteJobResponses,
  DeleteUserData,
  DeleteUserResponses,
  DeleteWorkspaceData,
  DeleteWorkspaceResponses,
  EchoData,
  EchoResponses,
  GetBrandingData,
  GetBrandingResponses,
  GetCurrentUserData,
  GetCurrentUserResponses,
  GetEnvironmentData,
  GetEnvironmentResponses,
  GetJobData,
  GetJobResponses,
  GetRunData,
  GetRunResponses,
  GetWorkspaceData,
  GetWorkspaceResponses,
  ListEnvironmentSecretsData,
  ListEnvironmentSecretsResponses,
  ListJobRunsData,
  ListJobRunsResponses,
  ListJobsData,
  ListJobsResponses,
  ListToolsData,
  ListToolsResponses,
  ListUsersData,
  ListUsersResponses,
  ListWorkspacePluginsData,
  ListWorkspacePluginsResponses,
  ListWorkspaceRunsData,
  ListWorkspaceRunsResponses,
  ListWorkspacesData,
  ListWorkspacesResponses,
  LoginData,
  LoginResponses,
  LogoutData,
  LogoutResponses,
  PingData,
  PingResponses,
  ResetUserPasswordData,
  ResetUserPasswordResponses,
  RunJobData,
  RunJobResponses,
  SetEnvironmentSecretData,
  SetEnvironmentSecretResponses,
  SetUserActiveData,
  SetUserActiveResponses,
  SetUserRoleData,
  SetUserRoleResponses,
  SyncWorkspaceData,
  SyncWorkspaceResponses,
  TestWorkspaceConnectionData,
  TestWorkspaceConnectionResponses,
  UpdateBrandingData,
  UpdateBrandingResponses,
  UpdateEnvironmentData,
  UpdateEnvironmentResponses,
  UpdateJobData,
  UpdateJobResponses,
  UpdateWorkspaceData,
  UpdateWorkspaceResponses,
  UploadLogoData,
  UploadLogoResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class Auth {
  public static login<ThrowOnError extends boolean = false>(
    options: Options<LoginData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<LoginResponses, unknown, ThrowOnError>({
      url: '/api/auth/login',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static logout<ThrowOnError extends boolean = false>(
    options?: Options<LogoutData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
      url: '/api/auth/logout',
      ...options,
    });
  }

  public static getCurrentUser<ThrowOnError extends boolean = false>(
    options?: Options<GetCurrentUserData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<GetCurrentUserResponses, unknown, ThrowOnError>({
      url: '/api/auth/me',
      ...options,
    });
  }

  public static changePassword<ThrowOnError extends boolean = false>(
    options: Options<ChangePasswordData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<ChangePasswordResponses, unknown, ThrowOnError>({
      url: '/api/auth/change-password',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}

export class Admin {
  public static listUsers<ThrowOnError extends boolean = false>(
    options?: Options<ListUsersData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<ListUsersResponses, unknown, ThrowOnError>({
      url: '/api/admin/users',
      ...options,
    });
  }

  public static createUser<ThrowOnError extends boolean = false>(
    options: Options<CreateUserData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<CreateUserResponses, unknown, ThrowOnError>({
      url: '/api/admin/users',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static resetUserPassword<ThrowOnError extends boolean = false>(
    options: Options<ResetUserPasswordData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<ResetUserPasswordResponses, unknown, ThrowOnError>({
      url: '/api/admin/users/{id}/reset-password',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static setUserActive<ThrowOnError extends boolean = false>(
    options: Options<SetUserActiveData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<SetUserActiveResponses, unknown, ThrowOnError>({
      url: '/api/admin/users/{id}/active',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static setUserRole<ThrowOnError extends boolean = false>(
    options: Options<SetUserRoleData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<SetUserRoleResponses, unknown, ThrowOnError>({
      url: '/api/admin/users/{id}/role',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static deleteUser<ThrowOnError extends boolean = false>(
    options: Options<DeleteUserData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<DeleteUserResponses, unknown, ThrowOnError>({
      url: '/api/admin/users/{id}',
      ...options,
    });
  }
}

export class Branding {
  public static getBranding<ThrowOnError extends boolean = false>(
    options?: Options<GetBrandingData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<GetBrandingResponses, unknown, ThrowOnError>({
      url: '/api/branding',
      ...options,
    });
  }

  public static updateBranding<ThrowOnError extends boolean = false>(
    options: Options<UpdateBrandingData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<UpdateBrandingResponses, unknown, ThrowOnError>({
      url: '/api/branding',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static uploadLogo<ThrowOnError extends boolean = false>(
    options: Options<UploadLogoData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<UploadLogoResponses, unknown, ThrowOnError>({
      ...formDataBodySerializer,
      url: '/api/branding/assets/logo',
      ...options,
      headers: {
        'Content-Type': null,
        ...options.headers,
      },
    });
  }
}

export class Environment {
  public static getEnvironment<ThrowOnError extends boolean = false>(
    options?: Options<GetEnvironmentData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<GetEnvironmentResponses, unknown, ThrowOnError>({
      url: '/api/environment',
      ...options,
    });
  }

  public static updateEnvironment<ThrowOnError extends boolean = false>(
    options: Options<UpdateEnvironmentData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<UpdateEnvironmentResponses, unknown, ThrowOnError>({
      url: '/api/environment',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static listEnvironmentSecrets<ThrowOnError extends boolean = false>(
    options?: Options<ListEnvironmentSecretsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<ListEnvironmentSecretsResponses, unknown, ThrowOnError>({
      url: '/api/environment/secrets',
      ...options,
    });
  }

  public static deleteEnvironmentSecret<ThrowOnError extends boolean = false>(
    options: Options<DeleteEnvironmentSecretData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      DeleteEnvironmentSecretResponses,
      unknown,
      ThrowOnError
    >({ url: '/api/environment/secrets/{name}', ...options });
  }

  public static setEnvironmentSecret<ThrowOnError extends boolean = false>(
    options: Options<SetEnvironmentSecretData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<SetEnvironmentSecretResponses, unknown, ThrowOnError>({
      url: '/api/environment/secrets/{name}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}

export class Agents {
  public static checkAgentHealth<ThrowOnError extends boolean = false>(
    options?: Options<CheckAgentHealthData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<CheckAgentHealthResponses, unknown, ThrowOnError>({
      url: '/api/agents/health',
      ...options,
    });
  }

  public static agentChat<ThrowOnError extends boolean = false>(
    options: Options<AgentChatData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<AgentChatResponses, unknown, ThrowOnError>({
      url: '/api/agents/chat',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}

export class Workspaces {
  public static listWorkspaces<ThrowOnError extends boolean = false>(
    options?: Options<ListWorkspacesData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<ListWorkspacesResponses, unknown, ThrowOnError>({
      url: '/api/workspaces',
      ...options,
    });
  }

  public static createWorkspace<ThrowOnError extends boolean = false>(
    options: Options<CreateWorkspaceData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<CreateWorkspaceResponses, unknown, ThrowOnError>({
      url: '/api/workspaces',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static deleteWorkspace<ThrowOnError extends boolean = false>(
    options: Options<DeleteWorkspaceData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<DeleteWorkspaceResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}',
      ...options,
    });
  }

  public static getWorkspace<ThrowOnError extends boolean = false>(
    options: Options<GetWorkspaceData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetWorkspaceResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}',
      ...options,
    });
  }

  public static updateWorkspace<ThrowOnError extends boolean = false>(
    options: Options<UpdateWorkspaceData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<UpdateWorkspaceResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static testWorkspaceConnection<ThrowOnError extends boolean = false>(
    options: Options<TestWorkspaceConnectionData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<TestWorkspaceConnectionResponses, unknown, ThrowOnError>(
      {
        url: '/api/workspaces/test',
        ...options,
        headers: {
          'Content-Type': 'application/json',
          ...options.headers,
        },
      },
    );
  }

  public static syncWorkspace<ThrowOnError extends boolean = false>(
    options: Options<SyncWorkspaceData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<SyncWorkspaceResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/sync',
      ...options,
    });
  }

  public static listWorkspacePlugins<ThrowOnError extends boolean = false>(
    options: Options<ListWorkspacePluginsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ListWorkspacePluginsResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/plugins',
      ...options,
    });
  }
}

export class Jobs {
  public static listJobs<ThrowOnError extends boolean = false>(
    options: Options<ListJobsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ListJobsResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/jobs',
      ...options,
    });
  }

  public static createJob<ThrowOnError extends boolean = false>(
    options: Options<CreateJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<CreateJobResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/jobs',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static deleteJob<ThrowOnError extends boolean = false>(
    options: Options<DeleteJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<DeleteJobResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/jobs/{jobId}',
      ...options,
    });
  }

  public static getJob<ThrowOnError extends boolean = false>(
    options: Options<GetJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetJobResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/jobs/{jobId}',
      ...options,
    });
  }

  public static updateJob<ThrowOnError extends boolean = false>(
    options: Options<UpdateJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<UpdateJobResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/jobs/{jobId}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static runJob<ThrowOnError extends boolean = false>(
    options: Options<RunJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<RunJobResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/jobs/{jobId}/run',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static listJobRuns<ThrowOnError extends boolean = false>(
    options: Options<ListJobRunsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ListJobRunsResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/jobs/{jobId}/runs',
      ...options,
    });
  }

  public static listWorkspaceRuns<ThrowOnError extends boolean = false>(
    options: Options<ListWorkspaceRunsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ListWorkspaceRunsResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/runs',
      ...options,
    });
  }

  public static getRun<ThrowOnError extends boolean = false>(
    options: Options<GetRunData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetRunResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/runs/{runId}',
      ...options,
    });
  }
}

export class Tools {
  public static listTools<ThrowOnError extends boolean = false>(
    options?: Options<ListToolsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<ListToolsResponses, unknown, ThrowOnError>({
      url: '/api/tools',
      ...options,
    });
  }
}

export class Diagnostics {
  /**
   * Liveness probe
   *
   * Returns a small payload echoing the server's wall-clock time. Used by the SPA and external monitors to confirm the API is reachable through the dev proxy and reverse proxies.
   */
  public static ping<ThrowOnError extends boolean = false>(
    options?: Options<PingData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<PingResponses, unknown, ThrowOnError>({
      url: '/api/ping',
      ...options,
    });
  }

  /**
   * Echo a message back, optionally repeated
   *
   * Demonstrates the full request/validation/envelope/ProblemDetails chain. Provided as a smoke-test endpoint for the dev proxy and the generated TypeScript client.
   */
  public static echo<ThrowOnError extends boolean = false>(
    options: Options<EchoData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<EchoResponses, unknown, ThrowOnError>({
      url: '/api/echo',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}
