// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from './client';
import { client } from './client.gen';
import type {
  AddWorkspaceMemberData,
  AddWorkspaceMemberResponses,
  AgentChatData,
  AgentChatResponses,
  ChangePasswordData,
  ChangePasswordResponses,
  CheckAgentHealthData,
  CheckAgentHealthResponses,
  CreateDashboardData,
  CreateDashboardGroupData,
  CreateDashboardGroupResponses,
  CreateDashboardResponses,
  CreateJobData,
  CreateJobResponses,
  CreateScheduleData,
  CreateScheduleResponses,
  CreateUserData,
  CreateUserResponses,
  CreateWorkspaceData,
  CreateWorkspaceResponses,
  DeleteDashboardData,
  DeleteDashboardGroupData,
  DeleteDashboardGroupResponses,
  DeleteDashboardResponses,
  DeleteEnvironmentSecretData,
  DeleteEnvironmentSecretResponses,
  DeleteJobData,
  DeleteJobResponses,
  DeleteScheduleData,
  DeleteScheduleResponses,
  DeleteUserData,
  DeleteUserResponses,
  DeleteWorkspaceData,
  DeleteWorkspacePluginSettingsData,
  DeleteWorkspacePluginSettingsResponses,
  DeleteWorkspaceResponses,
  EchoData,
  EchoResponses,
  FireScheduleData,
  FireScheduleResponses,
  GetBrandingData,
  GetBrandingResponses,
  GetCurrentUserData,
  GetCurrentUserResponses,
  GetDashboardData,
  GetDashboardResponses,
  GetEntityData,
  GetEntityResponses,
  GetEnvironmentData,
  GetEnvironmentResponses,
  GetJobData,
  GetJobResponses,
  GetPlanData,
  GetPlanResponses,
  GetRunData,
  GetRunResponses,
  GetWorkspaceData,
  GetWorkspacePluginSettingsData,
  GetWorkspacePluginSettingsResponses,
  GetWorkspaceResponses,
  ListConventionsData,
  ListConventionsResponses,
  ListDashboardGroupsData,
  ListDashboardGroupsResponses,
  ListDashboardsData,
  ListDashboardsResponses,
  ListEnvironmentSecretsData,
  ListEnvironmentSecretsResponses,
  ListJobRunsData,
  ListJobRunsResponses,
  ListJobsData,
  ListJobsResponses,
  ListPlansData,
  ListPlansResponses,
  ListSchedulesData,
  ListSchedulesResponses,
  ListToolsData,
  ListToolsResponses,
  ListUsersData,
  ListUsersResponses,
  ListWorkspaceMembersData,
  ListWorkspaceMembersResponses,
  ListWorkspacePluginsData,
  ListWorkspacePluginsResponses,
  ListWorkspaceRunsData,
  ListWorkspaceRunsResponses,
  ListWorkspacesData,
  ListWorkspacesResponses,
  LoginData,
  LoginResponses,
  LogoutData,
  LogoutResponses,
  PingData,
  PingResponses,
  PushWorkspaceData,
  PushWorkspaceResponses,
  QueryEntitiesData,
  QueryEntitiesResponses,
  RemoveWorkspaceMemberData,
  RemoveWorkspaceMemberResponses,
  ResetUserPasswordData,
  ResetUserPasswordResponses,
  RunJobData,
  RunJobResponses,
  SetEnvironmentSecretData,
  SetEnvironmentSecretResponses,
  SetUserActiveData,
  SetUserActiveResponses,
  SetUserRoleData,
  SetUserRoleResponses,
  SetWorkspacePluginEnabledData,
  SetWorkspacePluginEnabledResponses,
  SetWorkspacePluginSettingsData,
  SetWorkspacePluginSettingsResponses,
  SyncProjectionData,
  SyncProjectionResponses,
  SyncWorkspaceData,
  SyncWorkspaceResponses,
  TestWorkspaceConnectionData,
  TestWorkspaceConnectionResponses,
  UpdateBrandingData,
  UpdateBrandingResponses,
  UpdateDashboardData,
  UpdateDashboardGroupData,
  UpdateDashboardGroupResponses,
  UpdateDashboardResponses,
  UpdateEnvironmentData,
  UpdateEnvironmentResponses,
  UpdateJobData,
  UpdateJobResponses,
  UpdateScheduleData,
  UpdateScheduleResponses,
  UpdateWorkspaceData,
  UpdateWorkspaceMemberData,
  UpdateWorkspaceMemberResponses,
  UpdateWorkspaceResponses,
  UploadLogoData,
  UploadLogoResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class Auth {
  public static login<ThrowOnError extends boolean = false>(
    options: Options<LoginData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<LoginResponses, unknown, ThrowOnError>({
      url: '/api/auth/login',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static logout<ThrowOnError extends boolean = false>(
    options?: Options<LogoutData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
      url: '/api/auth/logout',
      ...options,
    });
  }

  public static getCurrentUser<ThrowOnError extends boolean = false>(
    options?: Options<GetCurrentUserData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<GetCurrentUserResponses, unknown, ThrowOnError>({
      url: '/api/auth/me',
      ...options,
    });
  }

  public static changePassword<ThrowOnError extends boolean = false>(
    options: Options<ChangePasswordData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<ChangePasswordResponses, unknown, ThrowOnError>({
      url: '/api/auth/change-password',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}

export class Admin {
  public static listUsers<ThrowOnError extends boolean = false>(
    options?: Options<ListUsersData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<ListUsersResponses, unknown, ThrowOnError>({
      url: '/api/admin/users',
      ...options,
    });
  }

  public static createUser<ThrowOnError extends boolean = false>(
    options: Options<CreateUserData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<CreateUserResponses, unknown, ThrowOnError>({
      url: '/api/admin/users',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static resetUserPassword<ThrowOnError extends boolean = false>(
    options: Options<ResetUserPasswordData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<ResetUserPasswordResponses, unknown, ThrowOnError>({
      url: '/api/admin/users/{id}/reset-password',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static setUserActive<ThrowOnError extends boolean = false>(
    options: Options<SetUserActiveData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<SetUserActiveResponses, unknown, ThrowOnError>({
      url: '/api/admin/users/{id}/active',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static setUserRole<ThrowOnError extends boolean = false>(
    options: Options<SetUserRoleData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<SetUserRoleResponses, unknown, ThrowOnError>({
      url: '/api/admin/users/{id}/role',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static deleteUser<ThrowOnError extends boolean = false>(
    options: Options<DeleteUserData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<DeleteUserResponses, unknown, ThrowOnError>({
      url: '/api/admin/users/{id}',
      ...options,
    });
  }
}

export class Branding {
  public static getBranding<ThrowOnError extends boolean = false>(
    options?: Options<GetBrandingData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<GetBrandingResponses, unknown, ThrowOnError>({
      url: '/api/branding',
      ...options,
    });
  }

  public static updateBranding<ThrowOnError extends boolean = false>(
    options: Options<UpdateBrandingData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<UpdateBrandingResponses, unknown, ThrowOnError>({
      url: '/api/branding',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static uploadLogo<ThrowOnError extends boolean = false>(
    options: Options<UploadLogoData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<UploadLogoResponses, unknown, ThrowOnError>({
      ...formDataBodySerializer,
      url: '/api/branding/assets/logo',
      ...options,
      headers: {
        'Content-Type': null,
        ...options.headers,
      },
    });
  }
}

export class Environment {
  public static getEnvironment<ThrowOnError extends boolean = false>(
    options?: Options<GetEnvironmentData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<GetEnvironmentResponses, unknown, ThrowOnError>({
      url: '/api/environment',
      ...options,
    });
  }

  public static updateEnvironment<ThrowOnError extends boolean = false>(
    options: Options<UpdateEnvironmentData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<UpdateEnvironmentResponses, unknown, ThrowOnError>({
      url: '/api/environment',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static listEnvironmentSecrets<ThrowOnError extends boolean = false>(
    options?: Options<ListEnvironmentSecretsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<ListEnvironmentSecretsResponses, unknown, ThrowOnError>({
      url: '/api/environment/secrets',
      ...options,
    });
  }

  public static deleteEnvironmentSecret<ThrowOnError extends boolean = false>(
    options: Options<DeleteEnvironmentSecretData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      DeleteEnvironmentSecretResponses,
      unknown,
      ThrowOnError
    >({ url: '/api/environment/secrets/{name}', ...options });
  }

  public static setEnvironmentSecret<ThrowOnError extends boolean = false>(
    options: Options<SetEnvironmentSecretData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<SetEnvironmentSecretResponses, unknown, ThrowOnError>({
      url: '/api/environment/secrets/{name}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}

export class Agents {
  public static checkAgentHealth<ThrowOnError extends boolean = false>(
    options?: Options<CheckAgentHealthData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<CheckAgentHealthResponses, unknown, ThrowOnError>({
      url: '/api/agents/health',
      ...options,
    });
  }

  public static agentChat<ThrowOnError extends boolean = false>(
    options: Options<AgentChatData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<AgentChatResponses, unknown, ThrowOnError>({
      url: '/api/agents/chat',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}

export class Workspaces {
  public static listWorkspaces<ThrowOnError extends boolean = false>(
    options?: Options<ListWorkspacesData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<ListWorkspacesResponses, unknown, ThrowOnError>({
      url: '/api/workspaces',
      ...options,
    });
  }

  public static createWorkspace<ThrowOnError extends boolean = false>(
    options: Options<CreateWorkspaceData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<CreateWorkspaceResponses, unknown, ThrowOnError>({
      url: '/api/workspaces',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static deleteWorkspace<ThrowOnError extends boolean = false>(
    options: Options<DeleteWorkspaceData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<DeleteWorkspaceResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}',
      ...options,
    });
  }

  public static getWorkspace<ThrowOnError extends boolean = false>(
    options: Options<GetWorkspaceData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetWorkspaceResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}',
      ...options,
    });
  }

  public static updateWorkspace<ThrowOnError extends boolean = false>(
    options: Options<UpdateWorkspaceData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<UpdateWorkspaceResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static testWorkspaceConnection<ThrowOnError extends boolean = false>(
    options: Options<TestWorkspaceConnectionData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<TestWorkspaceConnectionResponses, unknown, ThrowOnError>(
      {
        url: '/api/workspaces/test',
        ...options,
        headers: {
          'Content-Type': 'application/json',
          ...options.headers,
        },
      },
    );
  }

  public static syncWorkspace<ThrowOnError extends boolean = false>(
    options: Options<SyncWorkspaceData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<SyncWorkspaceResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/sync',
      ...options,
    });
  }

  public static pushWorkspace<ThrowOnError extends boolean = false>(
    options: Options<PushWorkspaceData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<PushWorkspaceResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/push',
      ...options,
    });
  }

  public static listWorkspacePlugins<ThrowOnError extends boolean = false>(
    options: Options<ListWorkspacePluginsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ListWorkspacePluginsResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/plugins',
      ...options,
    });
  }

  public static setWorkspacePluginEnabled<ThrowOnError extends boolean = false>(
    options: Options<SetWorkspacePluginEnabledData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<
      SetWorkspacePluginEnabledResponses,
      unknown,
      ThrowOnError
    >({
      url: '/api/workspaces/{slug}/plugins/{pluginId}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static deleteWorkspacePluginSettings<ThrowOnError extends boolean = false>(
    options: Options<DeleteWorkspacePluginSettingsData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      DeleteWorkspacePluginSettingsResponses,
      unknown,
      ThrowOnError
    >({ url: '/api/workspaces/{slug}/plugins/{pluginId}/settings', ...options });
  }

  public static getWorkspacePluginSettings<ThrowOnError extends boolean = false>(
    options: Options<GetWorkspacePluginSettingsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetWorkspacePluginSettingsResponses,
      unknown,
      ThrowOnError
    >({ url: '/api/workspaces/{slug}/plugins/{pluginId}/settings', ...options });
  }

  public static setWorkspacePluginSettings<ThrowOnError extends boolean = false>(
    options: Options<SetWorkspacePluginSettingsData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<
      SetWorkspacePluginSettingsResponses,
      unknown,
      ThrowOnError
    >({
      url: '/api/workspaces/{slug}/plugins/{pluginId}/settings',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}

export class Jobs {
  public static listJobs<ThrowOnError extends boolean = false>(
    options: Options<ListJobsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ListJobsResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/jobs',
      ...options,
    });
  }

  public static createJob<ThrowOnError extends boolean = false>(
    options: Options<CreateJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<CreateJobResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/jobs',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static deleteJob<ThrowOnError extends boolean = false>(
    options: Options<DeleteJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<DeleteJobResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/jobs/{jobId}',
      ...options,
    });
  }

  public static getJob<ThrowOnError extends boolean = false>(
    options: Options<GetJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetJobResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/jobs/{jobId}',
      ...options,
    });
  }

  public static updateJob<ThrowOnError extends boolean = false>(
    options: Options<UpdateJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<UpdateJobResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/jobs/{jobId}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static runJob<ThrowOnError extends boolean = false>(
    options: Options<RunJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<RunJobResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/jobs/{jobId}/run',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static listJobRuns<ThrowOnError extends boolean = false>(
    options: Options<ListJobRunsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ListJobRunsResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/jobs/{jobId}/runs',
      ...options,
    });
  }

  public static listWorkspaceRuns<ThrowOnError extends boolean = false>(
    options: Options<ListWorkspaceRunsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ListWorkspaceRunsResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/runs',
      ...options,
    });
  }

  public static getRun<ThrowOnError extends boolean = false>(
    options: Options<GetRunData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetRunResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/runs/{runId}',
      ...options,
    });
  }
}

export class Tools {
  public static listTools<ThrowOnError extends boolean = false>(
    options?: Options<ListToolsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<ListToolsResponses, unknown, ThrowOnError>({
      url: '/api/tools',
      ...options,
    });
  }
}

export class Schedules {
  public static listSchedules<ThrowOnError extends boolean = false>(
    options: Options<ListSchedulesData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ListSchedulesResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/schedules',
      ...options,
    });
  }

  public static createSchedule<ThrowOnError extends boolean = false>(
    options: Options<CreateScheduleData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<CreateScheduleResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/schedules',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static deleteSchedule<ThrowOnError extends boolean = false>(
    options: Options<DeleteScheduleData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<DeleteScheduleResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/schedules/{scheduleId}',
      ...options,
    });
  }

  public static updateSchedule<ThrowOnError extends boolean = false>(
    options: Options<UpdateScheduleData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<UpdateScheduleResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/schedules/{scheduleId}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static fireSchedule<ThrowOnError extends boolean = false>(
    options: Options<FireScheduleData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<FireScheduleResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/schedules/{scheduleId}/fire',
      ...options,
    });
  }
}

export class Dashboards {
  public static listDashboards<ThrowOnError extends boolean = false>(
    options: Options<ListDashboardsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ListDashboardsResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/dashboards',
      ...options,
    });
  }

  public static createDashboard<ThrowOnError extends boolean = false>(
    options: Options<CreateDashboardData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<CreateDashboardResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/dashboards',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static deleteDashboard<ThrowOnError extends boolean = false>(
    options: Options<DeleteDashboardData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<DeleteDashboardResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/dashboards/{dashSlug}',
      ...options,
    });
  }

  public static getDashboard<ThrowOnError extends boolean = false>(
    options: Options<GetDashboardData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetDashboardResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/dashboards/{dashSlug}',
      ...options,
    });
  }

  public static updateDashboard<ThrowOnError extends boolean = false>(
    options: Options<UpdateDashboardData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<UpdateDashboardResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/dashboards/{dashSlug}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}

export class DashboardGroups {
  public static listDashboardGroups<ThrowOnError extends boolean = false>(
    options: Options<ListDashboardGroupsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ListDashboardGroupsResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/dashboard-groups',
      ...options,
    });
  }

  public static createDashboardGroup<ThrowOnError extends boolean = false>(
    options: Options<CreateDashboardGroupData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<CreateDashboardGroupResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/dashboard-groups',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static deleteDashboardGroup<ThrowOnError extends boolean = false>(
    options: Options<DeleteDashboardGroupData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<DeleteDashboardGroupResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/dashboard-groups/{groupSlug}',
      ...options,
    });
  }

  public static updateDashboardGroup<ThrowOnError extends boolean = false>(
    options: Options<UpdateDashboardGroupData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<UpdateDashboardGroupResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/dashboard-groups/{groupSlug}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}

export class Members {
  public static listWorkspaceMembers<ThrowOnError extends boolean = false>(
    options: Options<ListWorkspaceMembersData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ListWorkspaceMembersResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/members',
      ...options,
    });
  }

  public static addWorkspaceMember<ThrowOnError extends boolean = false>(
    options: Options<AddWorkspaceMemberData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<AddWorkspaceMemberResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/members',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  public static removeWorkspaceMember<ThrowOnError extends boolean = false>(
    options: Options<RemoveWorkspaceMemberData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<RemoveWorkspaceMemberResponses, unknown, ThrowOnError>(
      { url: '/api/workspaces/{slug}/members/{userId}', ...options },
    );
  }

  public static updateWorkspaceMember<ThrowOnError extends boolean = false>(
    options: Options<UpdateWorkspaceMemberData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<UpdateWorkspaceMemberResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/members/{userId}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}

export class Projections {
  public static listConventions<ThrowOnError extends boolean = false>(
    options: Options<ListConventionsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ListConventionsResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/conventions',
      ...options,
    });
  }

  public static queryEntities<ThrowOnError extends boolean = false>(
    options: Options<QueryEntitiesData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<QueryEntitiesResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/entities',
      ...options,
    });
  }

  public static getEntity<ThrowOnError extends boolean = false>(
    options: Options<GetEntityData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetEntityResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/entities/{kind}/{entitySlug}',
      ...options,
    });
  }

  public static syncProjection<ThrowOnError extends boolean = false>(
    options: Options<SyncProjectionData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<SyncProjectionResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/projections/sync',
      ...options,
    });
  }
}

export class Plans {
  public static listPlans<ThrowOnError extends boolean = false>(
    options: Options<ListPlansData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ListPlansResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/plans',
      ...options,
    });
  }

  public static getPlan<ThrowOnError extends boolean = false>(
    options: Options<GetPlanData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetPlanResponses, unknown, ThrowOnError>({
      url: '/api/workspaces/{slug}/plans/{planId}',
      ...options,
    });
  }
}

export class Diagnostics {
  /**
   * Liveness probe
   *
   * Returns a small payload echoing the server's wall-clock time. Used by the SPA and external monitors to confirm the API is reachable through the dev proxy and reverse proxies.
   */
  public static ping<ThrowOnError extends boolean = false>(
    options?: Options<PingData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<PingResponses, unknown, ThrowOnError>({
      url: '/api/ping',
      ...options,
    });
  }

  /**
   * Echo a message back, optionally repeated
   *
   * Demonstrates the full request/validation/envelope/ProblemDetails chain. Provided as a smoke-test endpoint for the dev proxy and the generated TypeScript client.
   */
  public static echo<ThrowOnError extends boolean = false>(
    options: Options<EchoData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<EchoResponses, unknown, ThrowOnError>({
      url: '/api/echo',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}
