// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type AgentChatRequest = {
  message: string;
  history?: null | Array<ChatTurn>;
  provider?: null | string;
  currentScreen?: null | string;
};

export type AgentChatResult = {
  ok: boolean;
  reply: string;
  provider: null | string;
  model: null | string;
  latencyMs: null | number | string;
  error: null | string;
};

export type AgentHealthResult = {
  ok: boolean;
  provider: null | string;
  model: null | string;
  latencyMs: null | number | string;
  reply: null | string;
  error: null | string;
};

export type AiProvidersConfig = {
  defaultProvider?: null | string;
  anthropic?: null | AnthropicConfig;
  openAI?: null | OpenAiConfig;
  local?: null | LocalProviderConfig;
};

export type AnthropicConfig = {
  apiKeySecret?: null | string;
  defaultModel?: null | string;
  baseUrl?: null | string;
};

export type ApiResultOfAgentChatResult = {
  result: null | AgentChatResult;
};

export type ApiResultOfAgentHealthResult = {
  result: null | AgentHealthResult;
};

export type ApiResultOfboolean = {
  result: boolean;
};

export type ApiResultOfBrandingAssetResult = {
  result: null | BrandingAssetResult;
};

export type ApiResultOfBrandingConfig = {
  result: null | BrandingConfig;
};

export type ApiResultOfCreateUserResult = {
  result: null | CreateUserResult;
};

export type ApiResultOfEchoResponse = {
  result: null | EchoResponse;
};

export type ApiResultOfEnvironmentConfigView = {
  result: null | EnvironmentConfigView;
};

export type ApiResultOfGuid = {
  result: null | string;
};

export type ApiResultOfIReadOnlyListOfJobRunResult = {
  result: null | Array<JobRunResult>;
};

export type ApiResultOfIReadOnlyListOfJobScriptResult = {
  result: null | Array<JobScriptResult>;
};

export type ApiResultOfIReadOnlyListOfScheduleResult = {
  result: null | Array<ScheduleResult>;
};

export type ApiResultOfIReadOnlyListOfstring = {
  result: null | Array<string>;
};

export type ApiResultOfIReadOnlyListOfToolEntry = {
  result: null | Array<ToolEntry>;
};

export type ApiResultOfIReadOnlyListOfUserResult = {
  result: null | Array<UserResult>;
};

export type ApiResultOfIReadOnlyListOfWorkspaceResult = {
  result: null | Array<WorkspaceResult>;
};

export type ApiResultOfJobRunDetailResult = {
  result: null | JobRunDetailResult;
};

export type ApiResultOfJobRunResult = {
  result: null | JobRunResult;
};

export type ApiResultOfJobScriptResult = {
  result: null | JobScriptResult;
};

export type ApiResultOfPingResponse = {
  result: null | PingResponse;
};

export type ApiResultOfScheduleResult = {
  result: null | ScheduleResult;
};

export type ApiResultOfUserResult = {
  result: null | UserResult;
};

export type ApiResultOfWorkspaceConnectionTestResult = {
  result: null | WorkspaceConnectionTestResult;
};

export type ApiResultOfWorkspacePluginsResult = {
  result: null | WorkspacePluginsResult;
};

export type ApiResultOfWorkspaceResult = {
  result: null | WorkspaceResult;
};

export type ApiResultOfWorkspaceSyncResult = {
  result: null | WorkspaceSyncResult;
};

export type BrandingAssetResult = {
  url: string;
  contentType: string;
  size: number | string;
};

export type BrandingConfig = {
  productName: string;
  logoUrl: null | string;
  faviconUrl: null | string;
  loginBackgroundUrl: null | string;
  loginTagline: null | string;
  mode: string;
  palette: BrandPalette;
  chrome: ChromeTokens;
  chromeLight: ChromeTokens;
  fontFamily: null | string;
  fontFamilyMono: null | string;
  customCss: null | string;
  footerText: null | string;
  supportEmail: null | string;
};

export type BrandPalette = {
  primary?: null | string;
  secondary?: null | string;
  accent?: null | string;
  positive?: null | string;
  negative?: null | string;
  info?: null | string;
  warning?: null | string;
  dark?: null | string;
  darkPage?: null | string;
};

export type ChangePasswordRequest = {
  currentPassword: string;
  newPassword: string;
  confirmPassword: string;
};

export type ChatTurn = {
  role: string;
  content: string;
};

export type ChromeTokens = {
  bgPage?: null | string;
  bgSurface?: null | string;
  bgHeader?: null | string;
  bgSidebar?: null | string;
  bgElevated?: null | string;
  fgPrimary?: null | string;
  fgSecondary?: null | string;
  fgTertiary?: null | string;
  borderSubtle?: null | string;
  borderDefault?: null | string;
  borderStrong?: null | string;
};

export type CreateJobScriptRequest = {
  slug: string;
  name: string;
  description: null | string;
  pattern: string;
  frontmatter: string;
  body: string;
  status: string;
};

export type CreateScheduleRequest = {
  jobScriptId: string;
  kind: string;
  cronExpression: null | string;
  enabled: boolean;
};

export type CreateUserRequest = {
  email: string;
  displayName: string;
  role: string;
  temporaryPassword: null | string;
};

export type CreateUserResult = {
  userId: string;
  email: string;
  displayName: string;
  role: string;
  temporaryPassword: string;
};

export type CreateWorkspaceRequest = {
  slug: string;
  name: string;
  description: null | string;
  type: string;
  gitSettings?: null | GitWorkspaceSettingsDto;
  localSettings?: null | LocalWorkspaceSettingsDto;
};

export type EchoRequest = {
  message: string;
  repeat: null | number | string;
};

export type EchoResponse = {
  message: string;
};

export type EnvironmentConfig = {
  general: GeneralConfig;
  smtp: SmtpConfig;
  aiProviders: AiProvidersConfig;
};

export type EnvironmentConfigView = {
  config: EnvironmentConfig;
  secretsPresent: {
    [key: string]: boolean;
  };
};

export type GeneralConfig = {
  baseUrl?: null | string;
  timezone?: null | string;
};

export type GitWorkspaceSettingsDto = {
  repositoryUrl: string;
  authMode?: string;
  authSecret?: null | string;
  authCredential?: null | string;
  workingBranch?: string;
  sourceBranch?: string;
  mode?: string;
  pushFrequency?: string;
};

export type IFormFile = Blob | File;

export type JobRunDetailResult = {
  run: JobRunResult;
  steps: Array<JobRunStepResult>;
};

export type JobRunResult = {
  runId: string;
  jobScriptId: string;
  workspaceId: string;
  status: string;
  triggerKind: string;
  startedAt: string;
  completedAt: null | string;
  durationMs: number | string;
  totalTokensUsed: null | number | string;
  totalCostUsd: null | number | string;
  failureMessage: null | string;
  startCommitSha: null | string;
  endCommitSha: null | string;
};

export type JobRunStepResult = {
  stepId: string;
  position: number | string;
  stepType: string;
  name: string;
  status: string;
  idempotencyKey: string;
  cachedFromStepId: null | string;
  inputsJson: string;
  outputsJson: null | string;
  fileChangeCount: number | string;
  commitSha: null | string;
  startedAt: string;
  completedAt: null | string;
  durationMs: number | string;
  tokensUsed: null | number | string;
  costUsd: null | number | string;
  errorMessage: null | string;
};

export type JobScriptResult = {
  jobScriptId: string;
  workspaceId: string;
  slug: string;
  name: string;
  description: null | string;
  pattern: string;
  frontmatter: string;
  body: string;
  status: string;
  createdAt: string;
  updatedAt: string;
};

export type LocalProviderConfig = {
  baseUrl?: null | string;
  defaultModel?: null | string;
  apiKeySecret?: null | string;
  kind?: null | string;
};

export type LocalWorkspaceSettingsDto = {
  path: string;
  writable?: boolean;
};

export type LoginRequest = {
  email: string;
  password: string;
};

export type OpenAiConfig = {
  apiKeySecret?: null | string;
  defaultModel?: null | string;
  baseUrl?: null | string;
  azureDeployment?: null | string;
};

export type PingResponse = {
  message: string;
  serverTime: string;
};

export type ResetPasswordRequest = {
  temporaryPassword?: null | string;
};

export type RunJobScriptRequest = {
  parameters: null | {
    [key: string]: unknown;
  };
};

export type ScheduleResult = {
  scheduleId: string;
  workspaceId: string;
  jobScriptId: string;
  jobName: string;
  kind: string;
  cronExpression: null | string;
  enabled: boolean;
  nextDueAt: null | string;
  lastFiredAt: null | string;
  lastRunId: null | string;
  createdAt: string;
};

export type SetActiveRequest = {
  isActive: boolean;
};

export type SetSecretRequest = {
  value: string;
};

export type SetUserRoleRequest = {
  role: string;
};

export type SmtpConfig = {
  host?: null | string;
  port?: null | number | string;
  username?: null | string;
  passwordSecret?: null | string;
  encryption?: null | string;
  fromAddress?: null | string;
  fromName?: null | string;
};

export type TestWorkspaceConnectionRequest = {
  type: string;
  gitSettings?: null | GitWorkspaceSettingsDto;
  localSettings?: null | LocalWorkspaceSettingsDto;
};

export type ToolEntry = {
  name: string;
  category: string;
  description: null | string;
  source: string;
};

export type UpdateJobScriptRequest = {
  name: string;
  description: null | string;
  pattern: string;
  frontmatter: string;
  body: string;
  status: string;
};

export type UpdateScheduleRequest = {
  kind: string;
  cronExpression: null | string;
  enabled: boolean;
};

export type UpdateWorkspaceRequest = {
  name: string;
  description: null | string;
  type: string;
  gitSettings?: null | GitWorkspaceSettingsDto;
  localSettings?: null | LocalWorkspaceSettingsDto;
};

export type UserResult = {
  userId: string;
  email: string;
  displayName: string;
  role: string;
  isActive: boolean;
  mustChangePassword: boolean;
  lastLoginAt: null | string;
};

export type WorkspaceConnectionTestResult = {
  ok: boolean;
  latencyMs: number | string;
  error: null | string;
};

export type WorkspacePluginInfo = {
  pluginId: string;
  name: string;
  version: string;
  author: null | string;
  description: null | string;
  enabled: boolean;
  status: string;
  statusMessage: null | string;
  provides: Array<string>;
  requiredTools: Array<string>;
  loadedAt: null | string;
};

export type WorkspacePluginsResult = {
  plugins: Array<WorkspacePluginInfo>;
  note: null | string;
};

export type WorkspaceResult = {
  workspaceId: string;
  slug: string;
  name: string;
  description: null | string;
  type: string;
  gitSettings: null | GitWorkspaceSettingsDto;
  localSettings: null | LocalWorkspaceSettingsDto;
  authSecretPresent: boolean;
  createdAt: string;
  updatedAt: string;
  lastSyncAt: null | string;
  lastSyncSha: null | string;
  lastSyncStatus: null | string;
  lastSyncMessage: null | string;
};

export type WorkspaceSyncResult = {
  ok: boolean;
  slug: string;
  sha: null | string;
  latencyMs: number | string;
  syncedAt: string;
  message: null | string;
  error: null | string;
  dirtyCount?: number | string;
  requiresForce?: boolean;
};

export type LoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: '/api/auth/login';
};

export type LoginResponses = {
  /**
   * OK
   */
  200: ApiResultOfUserResult;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/logout';
};

export type LogoutResponses = {
  /**
   * OK
   */
  200: ApiResultOfboolean;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/me';
};

export type GetCurrentUserResponses = {
  /**
   * OK
   */
  200: ApiResultOfUserResult;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type ChangePasswordData = {
  body: ChangePasswordRequest;
  path?: never;
  query?: never;
  url: '/api/auth/change-password';
};

export type ChangePasswordResponses = {
  /**
   * OK
   */
  200: ApiResultOfboolean;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type ListUsersData = {
  body?: never;
  path?: never;
  query?: {
    skip?: number | string;
    take?: number | string;
  };
  url: '/api/admin/users';
};

export type ListUsersResponses = {
  /**
   * OK
   */
  200: ApiResultOfIReadOnlyListOfUserResult;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
  body: CreateUserRequest;
  path?: never;
  query?: never;
  url: '/api/admin/users';
};

export type CreateUserResponses = {
  /**
   * OK
   */
  200: ApiResultOfCreateUserResult;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type ResetUserPasswordData = {
  body?: null | ResetPasswordRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/users/{id}/reset-password';
};

export type ResetUserPasswordResponses = {
  /**
   * OK
   */
  200: ApiResultOfCreateUserResult;
};

export type ResetUserPasswordResponse =
  ResetUserPasswordResponses[keyof ResetUserPasswordResponses];

export type SetUserActiveData = {
  body: SetActiveRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/users/{id}/active';
};

export type SetUserActiveResponses = {
  /**
   * OK
   */
  200: ApiResultOfboolean;
};

export type SetUserActiveResponse = SetUserActiveResponses[keyof SetUserActiveResponses];

export type SetUserRoleData = {
  body: SetUserRoleRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/users/{id}/role';
};

export type SetUserRoleResponses = {
  /**
   * OK
   */
  200: ApiResultOfUserResult;
};

export type SetUserRoleResponse = SetUserRoleResponses[keyof SetUserRoleResponses];

export type DeleteUserData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/users/{id}';
};

export type DeleteUserResponses = {
  /**
   * OK
   */
  200: ApiResultOfboolean;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetBrandingData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/branding';
};

export type GetBrandingResponses = {
  /**
   * OK
   */
  200: ApiResultOfBrandingConfig;
};

export type GetBrandingResponse = GetBrandingResponses[keyof GetBrandingResponses];

export type UpdateBrandingData = {
  body: BrandingConfig;
  path?: never;
  query?: never;
  url: '/api/branding';
};

export type UpdateBrandingResponses = {
  /**
   * OK
   */
  200: ApiResultOfBrandingConfig;
};

export type UpdateBrandingResponse = UpdateBrandingResponses[keyof UpdateBrandingResponses];

export type UploadLogoData = {
  body: {
    file: IFormFile;
  };
  path?: never;
  query?: never;
  url: '/api/branding/assets/logo';
};

export type UploadLogoResponses = {
  /**
   * OK
   */
  200: ApiResultOfBrandingAssetResult;
};

export type UploadLogoResponse = UploadLogoResponses[keyof UploadLogoResponses];

export type GetEnvironmentData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/environment';
};

export type GetEnvironmentResponses = {
  /**
   * OK
   */
  200: ApiResultOfEnvironmentConfigView;
};

export type GetEnvironmentResponse = GetEnvironmentResponses[keyof GetEnvironmentResponses];

export type UpdateEnvironmentData = {
  body: EnvironmentConfig;
  path?: never;
  query?: never;
  url: '/api/environment';
};

export type UpdateEnvironmentResponses = {
  /**
   * OK
   */
  200: ApiResultOfEnvironmentConfigView;
};

export type UpdateEnvironmentResponse =
  UpdateEnvironmentResponses[keyof UpdateEnvironmentResponses];

export type ListEnvironmentSecretsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/environment/secrets';
};

export type ListEnvironmentSecretsResponses = {
  /**
   * OK
   */
  200: ApiResultOfIReadOnlyListOfstring;
};

export type ListEnvironmentSecretsResponse =
  ListEnvironmentSecretsResponses[keyof ListEnvironmentSecretsResponses];

export type DeleteEnvironmentSecretData = {
  body?: never;
  path: {
    name: string;
  };
  query?: never;
  url: '/api/environment/secrets/{name}';
};

export type DeleteEnvironmentSecretResponses = {
  /**
   * OK
   */
  200: ApiResultOfboolean;
};

export type DeleteEnvironmentSecretResponse =
  DeleteEnvironmentSecretResponses[keyof DeleteEnvironmentSecretResponses];

export type SetEnvironmentSecretData = {
  body: SetSecretRequest;
  path: {
    name: string;
  };
  query?: never;
  url: '/api/environment/secrets/{name}';
};

export type SetEnvironmentSecretResponses = {
  /**
   * OK
   */
  200: ApiResultOfboolean;
};

export type SetEnvironmentSecretResponse =
  SetEnvironmentSecretResponses[keyof SetEnvironmentSecretResponses];

export type CheckAgentHealthData = {
  body?: never;
  path?: never;
  query?: {
    provider?: string;
  };
  url: '/api/agents/health';
};

export type CheckAgentHealthResponses = {
  /**
   * OK
   */
  200: ApiResultOfAgentHealthResult;
};

export type CheckAgentHealthResponse = CheckAgentHealthResponses[keyof CheckAgentHealthResponses];

export type AgentChatData = {
  body: AgentChatRequest;
  path?: never;
  query?: never;
  url: '/api/agents/chat';
};

export type AgentChatResponses = {
  /**
   * OK
   */
  200: ApiResultOfAgentChatResult;
};

export type AgentChatResponse = AgentChatResponses[keyof AgentChatResponses];

export type ListWorkspacesData = {
  body?: never;
  path?: never;
  query?: {
    skip?: number | string;
    take?: number | string;
  };
  url: '/api/workspaces';
};

export type ListWorkspacesResponses = {
  /**
   * OK
   */
  200: ApiResultOfIReadOnlyListOfWorkspaceResult;
};

export type ListWorkspacesResponse = ListWorkspacesResponses[keyof ListWorkspacesResponses];

export type CreateWorkspaceData = {
  body: CreateWorkspaceRequest;
  path?: never;
  query?: never;
  url: '/api/workspaces';
};

export type CreateWorkspaceResponses = {
  /**
   * OK
   */
  200: ApiResultOfWorkspaceResult;
};

export type CreateWorkspaceResponse = CreateWorkspaceResponses[keyof CreateWorkspaceResponses];

export type DeleteWorkspaceData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/workspaces/{slug}';
};

export type DeleteWorkspaceResponses = {
  /**
   * OK
   */
  200: ApiResultOfboolean;
};

export type DeleteWorkspaceResponse = DeleteWorkspaceResponses[keyof DeleteWorkspaceResponses];

export type GetWorkspaceData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/workspaces/{slug}';
};

export type GetWorkspaceResponses = {
  /**
   * OK
   */
  200: ApiResultOfWorkspaceResult;
};

export type GetWorkspaceResponse = GetWorkspaceResponses[keyof GetWorkspaceResponses];

export type UpdateWorkspaceData = {
  body: UpdateWorkspaceRequest;
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/workspaces/{slug}';
};

export type UpdateWorkspaceResponses = {
  /**
   * OK
   */
  200: ApiResultOfWorkspaceResult;
};

export type UpdateWorkspaceResponse = UpdateWorkspaceResponses[keyof UpdateWorkspaceResponses];

export type TestWorkspaceConnectionData = {
  body: TestWorkspaceConnectionRequest;
  path?: never;
  query?: never;
  url: '/api/workspaces/test';
};

export type TestWorkspaceConnectionResponses = {
  /**
   * OK
   */
  200: ApiResultOfWorkspaceConnectionTestResult;
};

export type TestWorkspaceConnectionResponse =
  TestWorkspaceConnectionResponses[keyof TestWorkspaceConnectionResponses];

export type SyncWorkspaceData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: {
    force?: boolean;
  };
  url: '/api/workspaces/{slug}/sync';
};

export type SyncWorkspaceResponses = {
  /**
   * OK
   */
  200: ApiResultOfWorkspaceSyncResult;
};

export type SyncWorkspaceResponse = SyncWorkspaceResponses[keyof SyncWorkspaceResponses];

export type ListWorkspacePluginsData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/workspaces/{slug}/plugins';
};

export type ListWorkspacePluginsResponses = {
  /**
   * OK
   */
  200: ApiResultOfWorkspacePluginsResult;
};

export type ListWorkspacePluginsResponse =
  ListWorkspacePluginsResponses[keyof ListWorkspacePluginsResponses];

export type ListJobsData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/workspaces/{slug}/jobs';
};

export type ListJobsResponses = {
  /**
   * OK
   */
  200: ApiResultOfIReadOnlyListOfJobScriptResult;
};

export type ListJobsResponse = ListJobsResponses[keyof ListJobsResponses];

export type CreateJobData = {
  body: CreateJobScriptRequest;
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/workspaces/{slug}/jobs';
};

export type CreateJobResponses = {
  /**
   * OK
   */
  200: ApiResultOfJobScriptResult;
};

export type CreateJobResponse = CreateJobResponses[keyof CreateJobResponses];

export type DeleteJobData = {
  body?: never;
  path: {
    slug: string;
    jobId: string;
  };
  query?: never;
  url: '/api/workspaces/{slug}/jobs/{jobId}';
};

export type DeleteJobResponses = {
  /**
   * OK
   */
  200: ApiResultOfboolean;
};

export type DeleteJobResponse = DeleteJobResponses[keyof DeleteJobResponses];

export type GetJobData = {
  body?: never;
  path: {
    slug: string;
    jobId: string;
  };
  query?: never;
  url: '/api/workspaces/{slug}/jobs/{jobId}';
};

export type GetJobResponses = {
  /**
   * OK
   */
  200: ApiResultOfJobScriptResult;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type UpdateJobData = {
  body: UpdateJobScriptRequest;
  path: {
    slug: string;
    jobId: string;
  };
  query?: never;
  url: '/api/workspaces/{slug}/jobs/{jobId}';
};

export type UpdateJobResponses = {
  /**
   * OK
   */
  200: ApiResultOfJobScriptResult;
};

export type UpdateJobResponse = UpdateJobResponses[keyof UpdateJobResponses];

export type RunJobData = {
  body?: null | RunJobScriptRequest;
  path: {
    slug: string;
    jobId: string;
  };
  query?: never;
  url: '/api/workspaces/{slug}/jobs/{jobId}/run';
};

export type RunJobResponses = {
  /**
   * OK
   */
  200: ApiResultOfJobRunResult;
};

export type RunJobResponse = RunJobResponses[keyof RunJobResponses];

export type ListJobRunsData = {
  body?: never;
  path: {
    slug: string;
    jobId: string;
  };
  query?: never;
  url: '/api/workspaces/{slug}/jobs/{jobId}/runs';
};

export type ListJobRunsResponses = {
  /**
   * OK
   */
  200: ApiResultOfIReadOnlyListOfJobRunResult;
};

export type ListJobRunsResponse = ListJobRunsResponses[keyof ListJobRunsResponses];

export type ListWorkspaceRunsData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/workspaces/{slug}/runs';
};

export type ListWorkspaceRunsResponses = {
  /**
   * OK
   */
  200: ApiResultOfIReadOnlyListOfJobRunResult;
};

export type ListWorkspaceRunsResponse =
  ListWorkspaceRunsResponses[keyof ListWorkspaceRunsResponses];

export type GetRunData = {
  body?: never;
  path: {
    slug: string;
    runId: string;
  };
  query?: never;
  url: '/api/workspaces/{slug}/runs/{runId}';
};

export type GetRunResponses = {
  /**
   * OK
   */
  200: ApiResultOfJobRunDetailResult;
};

export type GetRunResponse = GetRunResponses[keyof GetRunResponses];

export type ListToolsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/tools';
};

export type ListToolsResponses = {
  /**
   * OK
   */
  200: ApiResultOfIReadOnlyListOfToolEntry;
};

export type ListToolsResponse = ListToolsResponses[keyof ListToolsResponses];

export type ListSchedulesData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/workspaces/{slug}/schedules';
};

export type ListSchedulesResponses = {
  /**
   * OK
   */
  200: ApiResultOfIReadOnlyListOfScheduleResult;
};

export type ListSchedulesResponse = ListSchedulesResponses[keyof ListSchedulesResponses];

export type CreateScheduleData = {
  body: CreateScheduleRequest;
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/workspaces/{slug}/schedules';
};

export type CreateScheduleResponses = {
  /**
   * OK
   */
  200: ApiResultOfScheduleResult;
};

export type CreateScheduleResponse = CreateScheduleResponses[keyof CreateScheduleResponses];

export type DeleteScheduleData = {
  body?: never;
  path: {
    slug: string;
    scheduleId: string;
  };
  query?: never;
  url: '/api/workspaces/{slug}/schedules/{scheduleId}';
};

export type DeleteScheduleResponses = {
  /**
   * OK
   */
  200: ApiResultOfboolean;
};

export type DeleteScheduleResponse = DeleteScheduleResponses[keyof DeleteScheduleResponses];

export type UpdateScheduleData = {
  body: UpdateScheduleRequest;
  path: {
    slug: string;
    scheduleId: string;
  };
  query?: never;
  url: '/api/workspaces/{slug}/schedules/{scheduleId}';
};

export type UpdateScheduleResponses = {
  /**
   * OK
   */
  200: ApiResultOfScheduleResult;
};

export type UpdateScheduleResponse = UpdateScheduleResponses[keyof UpdateScheduleResponses];

export type FireScheduleData = {
  body?: never;
  path: {
    slug: string;
    scheduleId: string;
  };
  query?: never;
  url: '/api/workspaces/{slug}/schedules/{scheduleId}/fire';
};

export type FireScheduleResponses = {
  /**
   * OK
   */
  200: ApiResultOfGuid;
};

export type FireScheduleResponse = FireScheduleResponses[keyof FireScheduleResponses];

export type PingData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/ping';
};

export type PingResponses = {
  /**
   * OK
   */
  200: ApiResultOfPingResponse;
};

export type PingResponse2 = PingResponses[keyof PingResponses];

export type EchoData = {
  body: EchoRequest;
  path?: never;
  query?: never;
  url: '/api/echo';
};

export type EchoResponses = {
  /**
   * OK
   */
  200: ApiResultOfEchoResponse;
};

export type EchoResponse2 = EchoResponses[keyof EchoResponses];
