// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type ApiResultOfboolean = {
  result: boolean;
};

export type ApiResultOfCreateUserResult = {
  result: null | CreateUserResult;
};

export type ApiResultOfEchoResponse = {
  result: null | EchoResponse;
};

export type ApiResultOfIReadOnlyListOfUserResult = {
  result: null | Array<UserResult>;
};

export type ApiResultOfPingResponse = {
  result: null | PingResponse;
};

export type ApiResultOfUserResult = {
  result: null | UserResult;
};

export type ChangePasswordRequest = {
  currentPassword: string;
  newPassword: string;
  confirmPassword: string;
};

export type CreateUserRequest = {
  email: string;
  displayName: string;
  role: string;
  temporaryPassword: null | string;
};

export type CreateUserResult = {
  userId: string;
  email: string;
  displayName: string;
  role: string;
  temporaryPassword: string;
};

export type EchoRequest = {
  message: string;
  repeat: null | number | string;
};

export type EchoResponse = {
  message: string;
};

export type LoginRequest = {
  email: string;
  password: string;
};

export type PingResponse = {
  message: string;
  serverTime: string;
};

export type SetActiveRequest = {
  isActive: boolean;
};

export type UserResult = {
  userId: string;
  email: string;
  displayName: string;
  role: string;
  mustChangePassword: boolean;
};

export type LoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: '/api/auth/login';
};

export type LoginResponses = {
  /**
   * OK
   */
  200: ApiResultOfUserResult;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/logout';
};

export type LogoutResponses = {
  /**
   * OK
   */
  200: ApiResultOfboolean;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/me';
};

export type GetCurrentUserResponses = {
  /**
   * OK
   */
  200: ApiResultOfUserResult;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type ChangePasswordData = {
  body: ChangePasswordRequest;
  path?: never;
  query?: never;
  url: '/api/auth/change-password';
};

export type ChangePasswordResponses = {
  /**
   * OK
   */
  200: ApiResultOfboolean;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type ListUsersData = {
  body?: never;
  path?: never;
  query?: {
    skip?: number | string;
    take?: number | string;
  };
  url: '/api/admin/users';
};

export type ListUsersResponses = {
  /**
   * OK
   */
  200: ApiResultOfIReadOnlyListOfUserResult;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
  body: CreateUserRequest;
  path?: never;
  query?: never;
  url: '/api/admin/users';
};

export type CreateUserResponses = {
  /**
   * OK
   */
  200: ApiResultOfCreateUserResult;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type ResetUserPasswordData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/users/{id}/reset-password';
};

export type ResetUserPasswordResponses = {
  /**
   * OK
   */
  200: ApiResultOfCreateUserResult;
};

export type ResetUserPasswordResponse =
  ResetUserPasswordResponses[keyof ResetUserPasswordResponses];

export type SetUserActiveData = {
  body: SetActiveRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/users/{id}/active';
};

export type SetUserActiveResponses = {
  /**
   * OK
   */
  200: ApiResultOfboolean;
};

export type SetUserActiveResponse = SetUserActiveResponses[keyof SetUserActiveResponses];

export type PingData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/ping';
};

export type PingResponses = {
  /**
   * OK
   */
  200: ApiResultOfPingResponse;
};

export type PingResponse2 = PingResponses[keyof PingResponses];

export type EchoData = {
  body: EchoRequest;
  path?: never;
  query?: never;
  url: '/api/echo';
};

export type EchoResponses = {
  /**
   * OK
   */
  200: ApiResultOfEchoResponse;
};

export type EchoResponse2 = EchoResponses[keyof EchoResponses];
