<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OpenApiGenerateDocuments>true</OpenApiGenerateDocuments>
    <OpenApiGenerateDocumentsOnBuild>true</OpenApiGenerateDocumentsOnBuild>
    <OpenApiDocumentsDirectory>$(MSBuildProjectDirectory)</OpenApiDocumentsDirectory>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.*" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="10.0.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.7" />
    <PackageReference Include="ncrontab" Version="3.4.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.9" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Creuser.Agents\Creuser.Agents.csproj" />
    <ProjectReference Include="..\Creuser.Auth.Abstractions\Creuser.Auth.Abstractions.csproj" />
    <ProjectReference Include="..\Creuser.Auth.Core\Creuser.Auth.Core.csproj" />
    <ProjectReference Include="..\Creuser.Auth.Providers.Local\Creuser.Auth.Providers.Local.csproj" />
    <ProjectReference Include="..\Creuser.Auth.Providers.Google\Creuser.Auth.Providers.Google.csproj" />
    <ProjectReference Include="..\Creuser.Persistence\Creuser.Persistence.csproj" />
    <ProjectReference Include="..\Creuser.Plugins.Loader\Creuser.Plugins.Loader.csproj" />
    <ProjectReference Include="..\Creuser.Projections\Creuser.Projections.csproj" />
    <ProjectReference Include="..\Creuser.Sagas\Creuser.Sagas.csproj" />
    <ProjectReference Include="..\Creuser.Scripting\Creuser.Scripting.csproj" />
  </ItemGroup>
</Project>
